### ISSUE TITLE
500 Server Error on incoming email

### ISSUE THREAD

**Issue by Squeezemind** [roundcube/roundcubemail#5242]
Hello,

there is a bug in roundcube on ubuntu 16.04 LTS (PHP-7) when trying to read incoming emails. After the click on the email subject, a 500 error is returned back by the web server (Apache).

As you can read from the log (mail.log), the error is a missing PHP Class on **rcube_washtml.php**:

```
May  8 11:29:43 mxbp1 postfix/smtpd[12264]: connect from mail-ig0-f169.google.com[209.85.213.169]
May  8 11:29:43 mxbp1 postfix/smtpd[12264]: 68E081011BD: client=mail-ig0-f169.google.com[209.85.213.169]
May  8 11:29:43 mxbp1 postfix/cleanup[12275]: 68E081011BD: message-id=<CAHTNnErwuSy6cvRh7wNSjBtokA6RnESSxeVs6vQV6yTXcH9WyQ@mail.gmail.com>
May  8 11:29:43 mxbp1 postfix/qmgr[1492]: 68E081011BD: from=<********@gmail.com>, size=3553, nrcpt=1 (queue active)
May  8 11:29:43 mxbp1 postfix/smtpd[12264]: disconnect from mail-ig0-f169.google.com[209.85.213.169] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
May  8 11:29:43 mxbp1 postfix/smtpd[12283]: connect from mxbp1.*********.it[127.0.0.1]
May  8 11:29:44 mxbp1 postfix/smtpd[12283]: 009901011C2: client=mxbp1.*********.it[127.0.0.1]
May  8 11:29:44 mxbp1 postfix/cleanup[12275]: 009901011C2: message-id=<CAHTNnErwuSy6cvRh7wNSjBtokA6RnESSxeVs6vQV6yTXcH9WyQ@mail.gmail.com>
May  8 11:29:44 mxbp1 postfix/smtpd[12283]: disconnect from mxbp1.*********.it[127.0.0.1] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
May  8 11:29:44 mxbp1 postfix/qmgr[1492]: 009901011C2: from=<********@gmail.com>, size=4158, nrcpt=1 (queue active)
May  8 11:29:44 mxbp1 amavis[9666]: (09666-09) Passed CLEAN {RelayedInbound}, [209.85.213.169]:35138 [209.85.213.169] <********@gmail.com> -> <nuovo@bp1.*********.it>, Queue-ID: 68E081011BD, Message-ID: <CAHTNnErwuSy6cvRh7wNSjBtokA6RnESSxeVs6vQV6yTXcH9WyQ@mail.gmail.com>, mail_id: 2bn5AQVimgAv, Hits: -0.118, size: 3553, queued_as: 009901011C2, dkim_sd=20120113:gmail.com, 281 ms, Tests: [DKIM_SIGNED=0.1,DKIM_VALID=-0.1,DKIM_VALID_AU=-0.1,FREEMAIL_FROM=0.001,HTML_MESSAGE=0.001,RCVD_IN_MSPIKE_H3=-0.01,RCVD_IN_MSPIKE_WL=-0.01,SPF_PASS=-0.001,URIBL_BLOCKED=0.001]
May  8 11:29:44 mxbp1 postfix/smtp[12280]: 68E081011BD: to=<nuovo@bp1.*********.it>, relay=127.0.0.1[127.0.0.1]:10024, delay=0.61, delays=0.31/0.02/0/0.29, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 009901011C2)
May  8 11:29:44 mxbp1 postfix/qmgr[1492]: 68E081011BD: removed
May  8 11:29:44 mxbp1 postfix/pipe[12284]: 009901011C2: to=<nuovo@bp1.*********.it>, relay=dovecot, delay=0.03, delays=0/0/0/0.02, dsn=2.0.0, status=sent (delivered via dovecot service)
May  8 11:29:44 mxbp1 postfix/qmgr[1492]: 009901011C2: removed
May  8 11:29:48 mxbp1 roundcube: PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /opt/www/roundcubemail-1.1.5/program/lib/Roundcube/rcube_washtml.php:491#012Stack trace:#012#0 /opt/www/roundcubemail-1.1.5/program/steps/mail/func.inc(856): rcube_washtml->wash('<head><meta htt...')#012#1 /opt/www/roundcubemail-1.1.5/program/steps/mail/func.inc(892): rcmail_wash_html('<head><meta htt...', Array, NULL)#012#2 /opt/www/roundcubemail-1.1.5/program/steps/mail/func.inc(1228): rcmail_print_body('<div dir="ltr">...', Object(rcube_message_part), Array)#012#3 /opt/www/roundcubemail-1.1.5/program/include/rcmail_output_html.php(1129): rcmail_message_body(Array)#012#4 [internal function]: rcmail_output_html->xml_command(Array)#012#5 /opt/www/roundcubemail-1.1.5/program/include/rcmail_output_html.php(1002): preg_replace_callback('/<roundcube:([-...', Array, '<roundcube:obje...')#012#6 /opt/www/roundcubemail-1.1.5/program/include/rcmail_output_html.php(617): rcmail_output_html->parse_xml('<roundcube:obje...')#012#7 /opt/www/roundcubemail-1.1.5/program/include/rcmail_output_html.php(47 in /opt/www/roundcubemail-1.1.5/program/lib/Roundcube/rcube_washtml.php on line 491
```

**Comment by alecpl** [comment]
As stated in REQUIREMENTS section of INSTALL file you need PHP's DOM (may be XML on some systems) extension.
