### ISSUE TITLE
Enigma doesn't display passphrase dialog on encrypted mail

### ISSUE THREAD

**Issue by swecs** [roundcube/roundcubemail#5341]
Enigma doesn't display passphrase dialog on encrypted mail.

I have one installation of RoundCube on Debian 8 Jessie where all works fine, but i have two different servers with Gentoo (very similar installations, but one 32bit, other 64bit). And this problem is exactly same on both of them.

I can generate keys, i can sign and encrypt messages, but when i log out from RoundCube, log in back again and trying open some emails then password dialog doesn't appear.

Every atempt leaves one /usr/bin/gpg-agent process which running forever. I must kill them manually.

Right now i can read encrypted emails only after at least one mail was sent.

Is there some more posibilities how diagnose this bug? Maybe it is somewhere between gnupg, pinentry, pear, roundcube?

**part of ps afx with relevant processes**

```

7179 ?        Ss     0:00 /usr/sbin/apache2 -D DEFAULT_VHOST -D INFO -D SSL -D SSL_DEFAULT_VHOST -D LANGUAGE -D PHP5 -D SECURITY -D LIMITIPCONN -D PROXY -d /usr/lib64/apache2 -f /etc/apache2/httpd.conf -k start
 7181 ?        S      0:00  \_ /usr/sbin/apache2 -D DEFAULT_VHOST -D INFO -D SSL -D SSL_DEFAULT_VHOST -D LANGUAGE -D PHP5 -D SECURITY -D LIMITIPCONN -D PROXY -d /usr/lib64/apache2 -f /etc/apache2/httpd.conf -k start
 7184 ?        Sl     0:01  \_ /usr/sbin/apache2 -D DEFAULT_VHOST -D INFO -D SSL -D SSL_DEFAULT_VHOST -D LANGUAGE -D PHP5 -D SECURITY -D LIMITIPCONN -D PROXY -d /usr/lib64/apache2 -f /etc/apache2/httpd.conf -k start
 7186 ?        Sl     0:02  \_ /usr/sbin/apache2 -D DEFAULT_VHOST -D INFO -D SSL -D SSL_DEFAULT_VHOST -D LANGUAGE -D PHP5 -D SECURITY -D LIMITIPCONN -D PROXY -d /usr/lib64/apache2 -f /etc/apache2/httpd.conf -k start
 7592 ?        SL     0:00      \_ /usr/bin/gpg --status-fd 3 --command-fd 4 --no-secmem-warning --no-tty --no-default-keyring --no-options --no-permission-warning --exit-on-status-write-error --trust-model always --homedir /home/wwwroundcube/www/plugins/enigma/home/xxxxxx --decrypt
 8393 ?        SL     0:00      \_ /usr/bin/gpg --status-fd 3 --command-fd 4 --no-secmem-warning --no-tty --no-default-keyring --no-options --no-permission-warning --exit-on-status-write-error --trust-model always --homedir /home/wwwroundcube/www/plugins/enigma/home/xxxxxx --decrypt
 8405 ?        SL     0:00      \_ /usr/bin/gpg --status-fd 3 --command-fd 4 --no-secmem-warning --no-tty --no-default-keyring --no-options --no-permission-warning --exit-on-status-write-error --trust-model always --homedir /home/wwwroundcube/www/plugins/enigma/home/xxxxxx --decrypt
 7591 ?        Ss     0:00 /usr/bin/gpg-agent --daemon --options /dev/null --csh --keep-display --no-grab --ignore-cache-for-signing --pinentry-touch-file /dev/null --disable-scdaemon --no-use-standard-socket --pinentry-program /home/wwwroundcube/www/vendor/pear-pear.php.net/Crypt_GPG/Crypt/GPG/../../bin/crypt-gpg-pinentry --homedir /home/wwwroundcube/www/plugins/enigma/home/xxxxxx
 7594 ?        S      0:00  \_ php /home/wwwroundcube/www/vendor/pear-pear.php.net/Crypt_GPG/Crypt/GPG/../../bin/crypt-gpg-pinentry
 8392 ?        Ss     0:00 /usr/bin/gpg-agent --daemon --options /dev/null --csh --keep-display --no-grab --ignore-cache-for-signing --pinentry-touch-file /dev/null --disable-scdaemon --no-use-standard-socket --pinentry-program /home/wwwroundcube/www/vendor/pear-pear.php.net/Crypt_GPG/Crypt/GPG/../../bin/crypt-gpg-pinentry --homedir /home/wwwroundcube/www/plugins/enigma/home/xxxxxx
 8395 ?        S      0:00  \_ php /home/wwwroundcube/www/vendor/pear-pear.php.net/Crypt_GPG/Crypt/GPG/../../bin/crypt-gpg-pinentry
 8404 ?        Ss     0:00 /usr/bin/gpg-agent --daemon --options /dev/null --csh --keep-display --no-grab --ignore-cache-for-signing --pinentry-touch-file /dev/null --disable-scdaemon --no-use-standard-socket --pinentry-program /home/wwwroundcube/www/vendor/pear-pear.php.net/Crypt_GPG/Crypt/GPG/../../bin/crypt-gpg-pinentry --homedir /home/wwwroundcube/www/plugins/enigma/home/xxxxxx
 8407 ?        S      0:00  \_ php /home/wwwroundcube/www/vendor/pear-pear.php.net/Crypt_GPG/Crypt/GPG/../../bin/crypt-gpg-pinentry


```
**enigma log**
```


[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: BEGIN PROCESSING
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: selecting streams
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: => got 1
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: GPG output stream ready for reading
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: => about to read 8192 bytes from GPG output
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: => read 615 bytes
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: selecting streams
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: => got 3
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: GPG output stream ready for reading
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: => about to read 8192 bytes from GPG output
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: => read 0 bytes
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: GPG error stream ready for reading
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: => about to read 8192 bytes from GPG error
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: => read 0 bytes
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: GPG status stream ready for reading
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: => about to read 8192 bytes from GPG status
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: => read 0 bytes
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: END PROCESSING
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: CLOSING GPG SUBPROCESS
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: USING GPG 2.0.28 with PHP 5.5.35-pl0-gentoo
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: OPENING GPG-AGENT SUBPROCESS WITH THE FOLLOWING COMMAND:
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: /usr/bin/gpg-agent --daemon --options /dev/null --csh --keep-display --no-grab --ignore-cache-for-signing --pinentry-touch-file /dev/null --disable-scdaemon --no-use-standard-socket --pinentr
y-program '/home/wwwroundcube/www/vendor/pear-pear.php.net/Crypt_GPG/Crypt/GPG/../../bin/crypt-gpg-pinentry' --homedir '/home/wwwroundcube/www/plugins/enigma/home/xxxxxx'
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: CLOSING GPG-AGENT LAUNCH PROCESS
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: GPG-AGENT LAUNCH PROCESS CLOSED
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: OPENING GPG SUBPROCESS WITH THE FOLLOWING COMMAND:
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: /usr/bin/gpg --status-fd '3' --command-fd '4' --no-secmem-warning --no-tty --no-default-keyring --no-options --no-permission-warning --exit-on-status-write-error --trust-model always --homedi
r '/home/wwwroundcube/www/plugins/enigma/home/xxxxxx' --decrypt
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: BEGIN PROCESSING
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: selecting streams
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: => got 1
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: GPG is ready for input
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: => about to write 3038 bytes to GPG input
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: => wrote 3038 bytes
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: => closing GPG input pipe
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: selecting streams
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: => got 1
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: GPG status stream ready for reading
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: => about to read 8192 bytes from GPG status
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: => read 173 bytes
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: STATUS: ENC_TO FFE4FD4DDDCDC612 1 0
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: STATUS: USERID_HINT FFE4FD4DDDCDC612 Pavel Cejka <xxxxxx.xxxxxx@xxxxxx.com>
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: STATUS: NEED_PASSPHRASE FFE4FD4DDDCDC612 657E171FBA057118 1 0
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: => closing GPG input pipe
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: selecting streams
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: => got 1
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: GPG is ready for command data
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: => about to write 1 bytes to GPG command
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: => wrote 1
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: => closing GPG input pipe
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: selecting streams
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: => got 1
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: GPG status stream ready for reading
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: => about to read 8192 bytes from GPG status
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: => read 28 bytes
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: STATUS: MISSING_PASSPHRASE
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: => closing GPG input pipe
[30-Jun-2016 12:15:53 +0200]: <5aadc19c> GPG: selecting streams

```

**versions of installed packages**
```
[IP-] [  ] app-crypt/pinentry-0.9.5:0
[IP-] [  ] app-eselect/eselect-pinentry-0.6:0

[IP-] [  ] app-crypt/gnupg-2.0.28:0
[IP-] [  ] dev-libs/libgpg-error-1.19:0

[IP-] [  ] dev-php/pear-1.9.4:0

[IP-] [  ] dev-php/PEAR-Archive_Tar-1.3.15:0
[IP-] [  ] dev-php/PEAR-Auth_SASL-1.0.6:0
[IP-] [  ] dev-php/PEAR-Console_Getopt-1.3.1:0
[IP-] [  ] dev-php/PEAR-Crypt_GPG-1.3.2:0
[IP-] [  ] dev-php/PEAR-Mail_Mime-1.9.0:0
[IP-] [  ] dev-php/PEAR-Mail_mimeDecode-1.5.5:0
[IP-] [  ] dev-php/PEAR-Net_IDNA2-0.1.1:0
[IP-] [  ] dev-php/PEAR-Net_SMTP-1.6.2:0
[IP-] [  ] dev-php/PEAR-Net_Sieve-1.3.3:0
[IP-] [  ] dev-php/PEAR-Net_Socket-1.0.14:0
[IP-] [  ] dev-php/PEAR-PEAR-1.9.4:0
[IP-] [  ] dev-php/PEAR-Structures_Graph-1.0.4-r2:0
[IP-] [  ] dev-php/PEAR-XML_Util-1.2.3-r1:0

[IP-] [  ] app-admin/apache-tools-2.4.20:0
[IP-] [  ] www-servers/apache-2.4.20:2

```

RoundCube is in version 1.2.0

**Comment by variablenix** [comment]
Looks like I'm also able to reproduce the reported behavior. Following are the steps to reproduce.

1. Send a new encrypted email to yourself and verify decryption succeeds 
2. Logout / Login and attempt to open the same encrypted email
3. "Loading..." is displayed indefinitely with the following Enigma debug output

```
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: OPENING GPG SUBPROCESS WITH THE FOLLOWING COMMAND:
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: /usr/bin/gpg --status-fd '3' --command-fd '4' --no-secmem-warning --no-tty --no-default-keyring --no-options --always-trust --homedir '/usr/share/webapps/roundcubemail/plugins/enigma/home/johndoe' --version
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: BEGIN PROCESSING
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: selecting streams
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: => got 1
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: GPG output stream ready for reading
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: => about to read 8192 bytes from GPG output
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: => read 619 bytes
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: selecting streams
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: => got 3
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: GPG output stream ready for reading
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: => about to read 8192 bytes from GPG output
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: => read 0 bytes
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: GPG error stream ready for reading
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: => about to read 8192 bytes from GPG error
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: => read 0 bytes
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: GPG status stream ready for reading
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: => about to read 8192 bytes from GPG status
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: => read 0 bytes
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: END PROCESSING
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: CLOSING GPG SUBPROCESS
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: USING GPG 2.0.30 with PHP 7.0.8
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: OPENING GPG-AGENT SUBPROCESS WITH THE FOLLOWING COMMAND:
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: /usr/bin/gpg-agent --daemon --options /dev/null --csh --keep-display --no-grab --ignore-cache-for-signing --pinentry-touch-file /dev/null --disable-scdaemon --no-use-standard-socket --pinentry-program '/usr/share/webapps/roundcubemail/vendor/pear-pear.php.net/Crypt_GPG/bin/crypt-gpg-pinentry' --homedir '/usr/share/webapps/roundcubemail/plugins/enigma/home/johndoe'
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: CLOSING GPG-AGENT LAUNCH PROCESS
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: GPG-AGENT LAUNCH PROCESS CLOSED
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: OPENING GPG SUBPROCESS WITH THE FOLLOWING COMMAND:
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: /usr/bin/gpg --status-fd '3' --command-fd '4' --no-secmem-warning --no-tty --no-default-keyring --no-options --no-permission-warning --exit-on-status-write-error --trust-model always --homedir '/usr/share/webapps/roundcubemail/plugins/enigma/home/johndoe' --decrypt
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: BEGIN PROCESSING
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: selecting streams
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: => got 1
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: GPG is ready for input
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: => about to write 6516 bytes to GPG input
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: => wrote 6516 bytes
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: => closing GPG input pipe
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: selecting streams
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: => got 1
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: GPG status stream ready for reading
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: => about to read 8192 bytes from GPG status
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: => read 163 bytes
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: STATUS: ENC_TO 080722B7A302FB16 1 0
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: STATUS: USERID_HINT 080722B7A302FB16 tony <tony@koderoot.net>
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: STATUS: NEED_PASSPHRASE 080722B7A302FB16 FF93671E389C3C1B 1 0
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: => closing GPG input pipe
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: selecting streams
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: => got 1
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: GPG is ready for command data
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: => about to write 1 bytes to GPG command
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: => wrote 1
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: => closing GPG input pipe
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: selecting streams
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: => got 1
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: GPG status stream ready for reading
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: => about to read 8192 bytes from GPG status
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: => read 28 bytes
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: STATUS: MISSING_PASSPHRASE
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: => closing GPG input pipe
[30-Jun-2016 20:01:29 -0700]: <5k5ol3k2> GPG: selecting streams
```
Existing gpg-agent process shows: 
`http     29224  0.0  0.0  14268  2012 ?        Ss   20:18   0:00 /usr/bin/gpg-agent --daemon --options /dev/null --csh --keep-display --no-grab --ignore-cache-for-signing --pinentry-touch-file /dev/null --disable-scdaemon --no-use-standard-socket --pinentry-program /usr/share/webapps/roundcubemail/vendor/pear-pear.php.net/Crypt_GPG/bin/crypt-gpg-pinentry --homedir /usr/share/webapps/roundcubemail/plugins/enigma/home/johndoe`

gpg-agent is still hung up as shown in Roundcube with "Loading..." so no password dialog is ever shown until you kill gpg-agent `sudo killall -9 gpg-agent` which then produces the following Enigma output.

```
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: => got 2
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: GPG error stream ready for reading
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: => about to read 8192 bytes from GPG error
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: => read 525 bytes
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: ERROR: gpg: problem with the agent: End of file
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: ERROR: gpg: Invalid passphrase; please try again ...
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: ERROR: gpg: problem with the agent: Not supported
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: ERROR: gpg: problem with the agent: Not supported
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: ERROR: gpg: encrypted with 4096-bit RSA key, ID 4548F5EA, created 2016-07-01
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: ERROR:       "john <johndoe@domain.email>"
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: ERROR: gpg: public key decryption failed: Operation cancelled
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: ERROR: gpg: encrypted with 4096-bit RSA key, ID A302FB16, created 2016-07-01
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: ERROR:       "sue <suedoe@domain.email>"
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: ERROR: gpg: public key decryption failed: Operation cancelled
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: ERROR: gpg: decryption failed: No secret key
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: GPG status stream ready for reading
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: => about to read 8192 bytes from GPG status
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: => read 597 bytes
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: STATUS: BAD_PASSPHRASE 080722B7A302FB16
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: STATUS: USERID_HINT 080722B7A302FB16 tony <tony@koderoot.net>
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: STATUS: NEED_PASSPHRASE 080722B7A302FB16 FF93671E389C3C1B 1 0
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: STATUS: ERROR get_passphrase 60
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: STATUS: MISSING_PASSPHRASE
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: STATUS: ENC_TO 16CCEC2E4548F5EA 1 0
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: STATUS: USERID_HINT 16CCEC2E4548F5EA sue <suedoe@domain.email>
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: STATUS: NEED_PASSPHRASE 16CCEC2E4548F5EA 1405E6D2E9F4B224 1 0
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: STATUS: ERROR get_passphrase 60
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: STATUS: MISSING_PASSPHRASE
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: STATUS: ERROR pkdecrypt_failed 99
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: STATUS: ERROR pkdecrypt_failed 99
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: STATUS: BEGIN_DECRYPTION
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: STATUS: DECRYPTION_FAILED
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: STATUS: END_DECRYPTION
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: => closing GPG input pipe
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: selecting streams
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: => got 4
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: GPG output stream ready for reading
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: => about to read 8192 bytes from GPG output
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: => read 0 bytes
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: GPG error stream ready for reading
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: => about to read 8192 bytes from GPG error
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: => read 0 bytes
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: GPG status stream ready for reading
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: => about to read 8192 bytes from GPG status
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: => read 0 bytes
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: GPG is ready for command data
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: => about to write 2 bytes to GPG command
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: => broken pipe on GPG command
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: => closing pipe GPG command
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: => closing GPG input pipe
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: END PROCESSING
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: CLOSING GPG SUBPROCESS
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: => subprocess returned an unexpected exit code: 2
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: STOPPING GPG-AGENT DAEMON
[30-Jun-2016 20:22:41 -0700]: <i00h1v5g> GPG: GPG-AGENT DAEMON STOPPED
```

From here a password dialog is presented with `Message decrypted. Verified signature from.....`  which finally does decrypt the message successfully without any hangup.

**Comment by variablenix** [comment]
FWIW, something new in the logs.. 
```
[03-Jul-2016 22:27:55 America/Los_Angeles] PHP Fatal error:  Uncaught Error: Call to a member function getName() on null in /usr/share/webapps/roundcubemail/plugins/enigma/lib/enigma_driver_gnupg.php:428
Stack trace:
#0 /usr/share/webapps/roundcubemail/plugins/enigma/lib/enigma_driver_gnupg.php(144): enigma_driver_gnupg->parse_signature(Object(Crypt_GPG_Signature))
#1 /usr/share/webapps/roundcubemail/plugins/enigma/lib/enigma_engine.php(891): enigma_driver_gnupg->decrypt('-----BEGIN PGP ...', Array, NULL)
#2 /usr/share/webapps/roundcubemail/plugins/enigma/lib/enigma_engine.php(804): enigma_engine->pgp_decrypt('-----BEGIN PGP ...', NULL)
#3 /usr/share/webapps/roundcubemail/plugins/enigma/lib/enigma_engine.php(570): enigma_engine->parse_pgp_encrypted(Array)
#4 /usr/share/webapps/roundcubemail/plugins/enigma/lib/enigma_engine.php(392): enigma_engine->parse_encrypted(Array)
#5 /usr/share/webapps/roundcubemail/plugins/enigma/enigma.php(165): enigma_engine->part_structure(Array)
#6 /usr/share/webapps/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php(439): enigma->part in /usr/share/webapps/roundcubemail/plugins/enigma/lib/enigma_driver_gnupg.php on line 428
```

**Comment by alecpl** [comment]
@swecs PEAR-Crypt_GPG-1.3.2 does not comply to requirements.
@variablenix your issue looks different. Did you managed to fix it? Did you try to execute the pinentry program by hand?

**Comment by mmetatron** [comment]
Same issue it seems:
https://github.com/roundcube/roundcubemail/issues/5380

**Comment by develroo** [comment]
Can confirm this on Debian 8 with RC 1.2.2+dfsg.1-1 GnuPG  2.1.15-4 

>[05-Nov-2016 02:00:31 +0000]: <gih09cmb> GPG: GPG status stream ready for reading
>[05-Nov-2016 02:00:31 +0000]: <gih09cmb> GPG: => about to read 8192 bytes from GPG status
>[05-Nov-2016 02:00:31 +0000]: <gih09cmb> GPG: => read 33 bytes
>[05-Nov-2016 02:00:31 +0000]: <gih09cmb> GPG: STATUS: PINENTRY_LAUNCHED 12781
>[05-Nov-2016 02:00:31 +0000]: <gih09cmb> GPG: => closing GPG input pipe
>[05-Nov-2016 02:00:31 +0000]: <gih09cmb> GPG: selecting streams
>[05-Nov-2016 02:00:31 +0000]: <gih09cmb> GPG: => got 1
>[05-Nov-2016 02:00:31 +0000]: <gih09cmb> GPG: GPG status stream ready for reading
>[05-Nov-2016 02:00:31 +0000]: <gih09cmb> GPG: => about to read 8192 bytes from GPG status
>[05-Nov-2016 02:00:31 +0000]: <gih09cmb> GPG: => read 38 bytes
>[05-Nov-2016 02:00:31 +0000]: <gih09cmb> GPG: STATUS: ENC_TO 73D786D6D7DF9308 16 0
>[05-Nov-2016 02:00:31 +0000]: <gih09cmb> GPG: => closing GPG input pipe
>[05-Nov-2016 02:00:31 +0000]: <gih09cmb> GPG: selecting streams
>[05-Nov-2016 02:00:31 +0000]: <gih09cmb> GPG: => got 3
>[05-Nov-2016 02:00:31 +0000]: <gih09cmb> GPG: GPG output stream ready for reading
>[05-Nov-2016 02:00:31 +0000]: <gih09cmb> GPG: => about to read 8192 bytes from GPG output
>[05-Nov-2016 02:00:31 +0000]: <gih09cmb> GPG: => read 0 bytes
>[05-Nov-2016 02:00:31 +0000]: <gih09cmb> GPG: GPG error stream ready for reading
>[05-Nov-2016 02:00:31 +0000]: <gih09cmb> GPG: => about to read 8192 bytes from GPG error
>[05-Nov-2016 02:00:31 +0000]: <gih09cmb> GPG: => read 373 bytes
>[05-Nov-2016 02:00:31 +0000]: <gih09cmb> GPG: ERROR: gpg: encrypted with 2048-bit ELG key, ID XXXXXXX6D7DF9308, created 2005-02-02
>[05-Nov-2016 02:00:31 +0000]: <gih09cmb> GPG: ERROR:       "Real Name <useri@domain>"
>[05-Nov-2016 02:00:31 +0000]: <gih09cmb> GPG: ERROR: gpg: encrypted with 4096-bit RSA key, ID XXXXXX088D78DA, created 2016-11-04
>[05-Nov-2016 02:00:31 +0000]: <gih09cmb> GPG: ERROR:       "username (useri@domain) ><useri@domain.com>"
>[05-Nov-2016 02:00:31 +0000]: <gih09cmb> GPG: ERROR: gpg: public key decryption failed: No >passphrase given
>[05-Nov-2016 02:00:31 +0000]: <gih09cmb> GPG: ERROR: gpg: decryption failed: No secret key
>[05-Nov-2016 02:00:31 +0000]: <gih09cmb> GPG: GPG status stream ready for reading`


However it can be mitigated/hacked by triggering the passphrase entry by sending an encrypted email and just not having the unlocked key time out. Not a perfect solution but does indicate that the problem is not with the gpg-agent rather with the logic path when first accessing it. Maybe there is some timing issue I dunno. But it is kind of annoying because otherwise works mostly ok. 

At some point we will need to have an indicator of the trust of a key and have it search for keys to add etc.

**Comment by alecpl** [comment]
@develroo your problem is gnupg 2.1, which is not supported by Roundcube 1.2. Get git-master or wait for 1.3.
