### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /usr/share/roundcube/program/lib/Roundcube/rcube_washtml.php:496

### ISSUE THREAD

**Issue by francescovalentino** [roundcube/roundcubemail#5920]
Hi,
I cannot read any longer my emails, I have a Linux Ubuntu 14.04 server with Postfix + Dovecot and Roundcube installation.
From log I get this:
```
[23-Aug-2017 17:55:14 Europe/Amsterdam] PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /usr/share/roundcube/program/lib/Roundcube/rcube_washtml.php:496
Stack trace:
#0 /usr/share/roundcube/program/steps/mail/func.inc(866): rcube_washtml->wash('<html >\n   <hea...')
#1 /usr/share/roundcube/program/steps/mail/func.inc(902): rcmail_wash_html('<html >\n   <hea...', Array, NULL)
#2 /usr/share/roundcube/program/steps/mail/func.inc(1262): rcmail_print_body('<html >\n   <hea...', Object(rcube_message_part), Array)
#3 /usr/share/roundcube/program/include/rcmail_output_html.php(1135): rcmail_message_body(Array)
#4 [internal function]: rcmail_output_html->xml_command(Array)
#5 /usr/share/roundcube/program/include/rcmail_output_html.php(1004): preg_replace_callback('/<roundcube:([-...', Array, '<roundcube:obje...')
#6 /usr/share/roundcube/program/include/rcmail_output_html.php(619): rcmail_output_html->parse_xml('<roundcube:obje...')
#7 /usr/share/roundcube/program/include/rcmail_output_html.php(478): rcmail_output_html->parse('message', false)
#8 /usr/share in /usr/share/roundcube/program/lib/Roundcube/rcube_washtml.php on line 496
```
I ran `apt-get install php7.0-xml` and restart Apache. However I can't read emails, I can enter inside Roundcube but when I go to eg. `/roundcube/?_task=mail&_caps=pdf%3D1%2Cflash%3D1%2Ctif%3D0&_uid=3972&_mbox=INBOX&_action=show 
` it results in a 500 Error page.

What could be the problem?

**Comment by francescovalentino** [comment]
I found the issue!
Typing  `php -v` I get a new warning message 

```
PHP Warning: PHP Startup: Unable to load dynamic library '/usr/lib/php/20160303/dom.so' - /usr/lib/php/20160303/dom.so: undefined symbol: php_libxml_node_free_list in Unknown on line 0

PHP Warning: PHP Startup: Unable to load dynamic library '/usr/lib/php/20160303/xmlreader.so' - /usr/lib/php/20160303/xmlreader.so: undefined symbol: dom_node_class_entry in Unknown on line 0

PHP Warning: PHP Startup: Unable to load dynamic library '/usr/lib/php/20160303/xsl.so' - /usr/lib/php/20160303/xsl.so: undefined symbol: dom_node_class_entry in Unknown on line 0
PHP 7.1.5-1+deb.sury.org~trusty+2 (cli) (built: May 22 2017 13:39:01) ( NTS )
```

I used this answer https://stackoverflow.com/a/45211440/4458531 and restart Apache2 `sudo service apache2 restart` ...after that it works
