### ISSUE TITLE
Roundcube can't send an email

### ISSUE THREAD

**Issue by karstengit** [roundcube/roundcubemail#5965]
I am using the combination dovecot and exim with TLS encryption.
Roundcube can connect to the imap and show all the mails with

$config['default_host'] = 'mydomain.com';
$config['default_port'] = 143;
$config['imap_auth_type'] = 'PLAIN';

but i can't send any email!
I tried out every combination but it does not work!
I always get an error like: SMTP Fehler (-1): Die Verbindung ist fehlgeschlagen.
or another error.
Sometimes i get an error in the log of Exim like
TLS error on connection from localhost [::1] (gnutls_handshake): A TLS fatal alert has been received.

My last setting is:
$config['smtp_server'] = 'tls://%d';
$config['smtp_port'] = 587;
$config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p';
$config['smtp_auth_type'] = 'PLAIN';

Then i get no error, but the page keeps standing forever in "sending" ...

Older versions of roundcube in 2014 did work before.

**Comment by alecpl** [comment]
That's probably not Roundcube issue. Maybe you have to use `smtp_conn_options`. What PHP version?

**Comment by karstengit** [comment]
Debian uses PHP Version 7.0.19-1
My first try was to install roundcube with the debian package, but it failed with the mariadb database.
I think all dependent packages should be installed.

**Comment by alecpl** [comment]
Is there any error in Roundcube error log? Did you try disabling cert/host validation via `smtp_conn_options`?

**Comment by karstengit** [comment]
O.K. I found the error log. Last entry:
`[25-Sep-2017 17:45:59 Europe/Berlin] ERROR: Failed to connect socket: Die Operation ist jetzt in Bearbeitung ()

[25-Sep-2017 17:45:59 +0200]: <c23u470f> SMTP Error: Connection failed: Failed to connect socket: Die Operation ist jetzt in Bearbeitung in /---l/program/lib/Roundcube/rcube.php on line 1665 (POST /cubemail/?_task=mail&_unlock=loading1506354318923&_lang=de&_framed=1&_action=send)`

**Comment by alecpl** [comment]
I think "failed to connect socket" has nothing to do with TLS. Still does not look like Roundcube issue.

**Comment by karstengit** [comment]
Why other PHP software can mail without any problem?

**Comment by alecpl** [comment]
Are you sure %d resolves to the valid hostname?

**Comment by karstengit** [comment]
No - i am not sure about anything.
Because i don't understand this mass of parameters needed.
It seems localhost is able to send mails in a standard way in programs like forum, wiki, etc.

**Comment by alecpl** [comment]
Then don't use variables, but set proper hostname and make sure it resolves to proper IP address.

**Comment by karstengit** [comment]
Trying the old version 0.9.5. now.
After login a blank screen.
Trying with PHP 5.3 causes "session not guilty" in every case.

Roundcube seems not to be usable with Debian 9.0 any more. :-(

**Comment by karstengit** [comment]
The IP is not really clear.
The webmailer should be used either from Intranet with 192.168.1.x and via Dynamic IP from outside.
I tried both: Setting localhost, and DynDNS Name.
Nothing works!

**Comment by alecpl** [comment]
It does not matter from where do you connect to Roundcube. It matters where Roundcube is installed.

**Comment by karstengit** [comment]
The server has an Intranet IP.
Trying actual roundcube with PHP 5.3 causes a blank screen.
I altered it to the standard PHP 7.0 and trying to send an email causes
[26-Sep-2017 16:31:46 Europe/Berlin] PHP Warning:  strtotime() [<a href='function.strtotime'>function.strtotime</a>]: It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Europe/Berlin' for 'CEST/2.0/DST' instead in /srv/www/cubemail/program/lib/Roundcube/rcube_session_db.php on line 103
[26-Sep-2017 16:31:46 Europe/Berlin] PHP Warning:  strtotime() [<a href='function.strtotime'>function.strtotime</a>]: It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Europe/Berlin' for 'CEST/2.0/DST' instead in /.../program/lib/Roundcube/rcube_session_db.php on line 104
[26-Sep-2017 16:31:46 Europe/Berlin] PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct() [<a href='datetime.--construct'>datetime.--construct</a>]: It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Europe/Berlin' for 'CEST/2,0/DST' instead' in /.../program/lib/Roundcube/rcube_user.php:525
Stack trace:
#0 /.../program/lib/Roundcube/rcube_user.php(525): DateTime->__construct('2017-09-21 11:3...')
#1 /.../program/include/rcmail.php(617): rcube_user->is_locked()
#2 /.../index.php(121): rcmail->login('karsten@home.de...', 'khmemail', 'localhost', true)
#3 {main}
  thrown in /.../program/lib/Roundcube/rcube_user.php on line 525

**Comment by karstengit** [comment]
As i have written it runs before server upgrade in the old roundcube with the following configuration:

$rcmail_config['smtp_server'] = '';
$rcmail_config['smtp_port'] = 25;
$rcmail_config['smtp_user'] = '';
$rcmail_config['smtp_pass'] = '';
$rcmail_config['smtp_auth_type'] = '';
$rcmail_config['smtp_auth_cid'] = null;
$rcmail_config['smtp_auth_pw'] = null;
$rcmail_config['smtp_helo_host'] = '';
$rcmail_config['smtp_timeout'] = 0;

Simple and without no complication.
Of course i tried every combination of not encrypted SMTP access in the current version too.
There was always an error in the frontend like
SMTP Fehler (250): Die Authentisierung ist fehlgeschlagen.
with log
[26-Sep-2017 17:00:20 Europe/Berlin] ERROR: SMTP server does not support authentication ()
[26-Sep-2017 17:00:20 +0200]: <nsfi2quu> SMTP Error: Authentication failure: SMTP server does not support authentication (Code: ) in /.../program/lib/Roundcube/rcube.php on line 1665 (POST /.../?_task=mail&_unlock=loading1506438019928&_lang=de&_framed=1&_action=send)

My conclusion is now that roundcube can't be used anymore. :-(
