### ISSUE TITLE
managesieve white page in "Parameter/Filter" - Net_Sieve trouble ?

### ISSUE THREAD

**Issue by mustard007** [roundcube/roundcubemail#5983]
HI !
I installed a new Debian 9 server (Dovecot,Postfix, IspConfig and Roundcube).
I configured all the conf to activate Filter/Managesieve plugin.

When I try to go in Parameters / Filters I just have a white page. I look in /var/log/roundcube/errors and see that:

#2 /usr/share/roundcube/plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php(278): rcube_sieve_engine->start()
#3 /usr/share/roundcube/plugins/managesieve/managesieve.php(209): rcube_sieve_engine->actions()
#4 /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php(491): managesieve->managesieve_actions()
#5 /usr/share/roundcube/index.php(277): rcube_plugin_api->exec_action('plugin.managesi...')
#6 {main}
  thrown in /usr/share/roundcube/plugins/managesieve/lib/Roundcube/rcube_sieve.php on line 65

Uncaught Error: Class 'Net_Sieve' not found in /usr/share/roundcube/plugins/managesieve/lib/Roundcube/rcube_sieve.php:65

--------------

Line 65 is:
$this->sieve = new Net_Sieve();
(Php_pear is installed!)

Thanks for help !

**Comment by mustard007** [comment]
Found !

In Debian 9 I need to install : php-net-sieve, and voila the page appear !

Thanks
