### ISSUE TITLE
passwords in log file

### ISSUE THREAD

**Issue by 532910** [roundcube/roundcubemail#6949]
User passwords MUST NEVER go into log file! (Untill mayby it's explicitly asked) It's a serious security issue.

**Comment by alecpl** [comment]
What version? What password driver? How the log entry looks like?

**Comment by 532910** [comment]
1.4-rc2, sqlite,
```
/srv/www/roundcubemail-1.4-rc2-complete/index.php(121): rcmail->login('sergio', 'SUPERSECRET', 'mail', true)
```

**Comment by alecpl** [comment]
This looks like a fragment of error stack trace. We can't do nothing about it. Only thing you can do is to disable logging error stack traces. I think it's related to https://xdebug.org/docs/all_settings#collect_params.

**Comment by 532910** [comment]
```
[03-Oct-2019 10:46:22 Europe/Moscow] PHP Fatal error:  Uncaught Error: Length must be greater than 0 in /srv/www/roundcubemail-1.4-rc2-complete/program/lib/Roundcube/rcube_utils.php:1270                                                                                Stack trace:                                                                                                                         #0 /srv/www/roundcubemail-1.4-rc2-complete/program/lib/Roundcube/rcube_utils.php(1270): random_bytes(false)                          #1 /srv/www/roundcubemail-1.4-rc2-complete/program/lib/Roundcube/rcube.php(852): rcube_utils::random_bytes(false, true)              #2 /srv/www/roundcubemail-1.4-rc2-complete/program/include/rcmail.php(680): rcube->encrypt('SUPERSECRET')                             #3 /srv/www/roundcubemail-1.4-rc2-complete/index.php(121): rcmail->login('sergio', 'chithi5ohY', 'mail', true)                       #4 {main}                                                                                                                              thrown in /srv/www/roundcubemail-1.4-rc2-complete/program/lib/Roundcube/rcube_utils.php on line 1270
```

**Comment by alecpl** [comment]
and xdebug.show_error_trace.

**Comment by 532910** [comment]
> Only thing you can do is to disable logging error stack traces.

Could it be disabled by default?

**Comment by alecpl** [comment]
We should not force users to disable that.

**Comment by 532910** [comment]
Could you explain why? Stacktrace is disabled by default in all programs that I know.

**Comment by alecpl** [comment]
So, why it is enabled in the first place, if everyone disables it? Something does not sound right with that reasoning.

This is not the level Roundcube as an application should care of, imo.

**Comment by 532910** [comment]
OK, looks I was wrong and mixed up binary stack traces and translation languages (perl, php, python) stack traces, that are enabled by default.

> Only thing you can do is to disable logging error stack traces.

Could you help me, how to disable them?
