### ISSUE TITLE
Manage Sieve not working in 1.4-git [GIT 20191007.1111]

### ISSUE THREAD

**Issue by dktcoding** [roundcube/roundcubemail#6959]
The error log is:

```
[08-Oct-2019 12:35:19] PHP Fatal error:  Uncaught Error: Using $this when not in object context in public_html/plugins/managesieve/lib/Roundcube/rcube_sieve_vacation.php:594
Stack trace:
#0 public_html/plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php(2240): rcube_sieve_vacation::vacation_interval(Array)
#1 public_html/plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php(1638): rcube_sieve_engine->action_div('15', 0)
#2 public_html/program/include/rcmail_output_html.php(1348): rcube_sieve_engine->filter_form(Array)
#3 [internal function]: rcmail_output_html->xml_command(Array)
#4 public_html/program/include/rcmail_output_html.php(1198): preg_replace_callback('/<roundcube:([-...', Array, '<roundcube:incl...')
#5 public_html/program/include/rcmail_output_html.php(770): rcmail in public_html/plugins/managesieve/lib/Roundcube/rcube_sieve_vacation.php on line 594
```

And the code change was a couple of days ago:

https://github.com/roundcube/roundcubemail/blob/a3c491d5cb2d8ec64bdc5cb6eb67960e7ec563c0/plugins/managesieve/lib/Roundcube/rcube_sieve_vacation.php#L594

**Comment by alecpl** [comment]
Fixed.
