### ISSUE TITLE
ACL plugin: Cannot access protected property rcube_imap_generic::$user

### ISSUE THREAD

**Issue by johndoh** [roundcube/roundcubemail#7589]
rc version git-master, elastic skin

```
PHP Fatal error:  Uncaught Error: Cannot access protected property rcube_imap_generic::$user in /plugins/acl/acl.php:435
Stack trace:
#0 /plugins/acl/acl.php(231): acl->list_rights(Array)
#1 /program/include/rcmail_output_html.php(1374): acl->templ_table(Array)
#2 [internal function]: rcmail_output_html->xml_command(Array)
#3 /program/include/rcmail_output_html.php(1224): preg_replace_callback('/<roundcube:([-...', Array, '<div id="acllis...')
#4 /program/include/rcmail_output_html.php(782): rcmail_output_html->parse_xml('<div id="acllis...')
#5 /plugins/acl/acl.php(213): rcmail_output_html->parse('table', false, false)
#6 /program/lib/Roundcube/rcube_plugin_api.php(472): acl->folder_form(Array)
#7 /program/steps/settings/edit_folder.inc(283):  in /plugins/acl/acl.php on line 435
```

**Comment by alecpl** [comment]
Fixed.
