### ISSUE TITLE
Enigma + Internal Server Errors

### ISSUE THREAD

**Issue by Incognify** [roundcube/roundcubemail#7838]
Enabled Enigma, created the keys dir in a non-publicly accessible directory and made it read/writeable. But when I use RoundCube I get the Internal Server Error message(s) when doing anything related to the plugin (Clicking, "PGP Keys", trying to create or import them, etc)

From the error log:

```
Stack trace:
#0 /var/www/html/roundcubemail-1.4.10/program/lib/Roundcube/rcube_plugin_api.php(469): enigma->identity_form()
#1 /var/www/html/roundcubemail-1.4.10/program/steps/settings/edit_identity.inc(139): rcube_plugin_api->exec_hook()
#2 /var/www/html/roundcubemail-1.4.10/program/include/rcmail_output_html.php(1359): rcube_identity_form()
#3 [internal function]: rcmail_output_html->xml_command()
#4 /var/www/html/roundcubemail-1.4.10/program/include/rcmail_output_html.php(1209): preg_replace_callback()
#5 /var/www/html/roundcubemail-1.4.10/program/include/rcmail_output_html.php(781): rcmail_output_html->parse_xml()
#6 /var/www/html/roundcubemail-1.4.10/program/include/rcmail_output_html.php(615): rcmail_output_html->parse()
#7 /var/www/html/roundcubemail-1.4.10/program/steps/settings/edit_identity.inc(63): rcmail_output_html->send()
#8 /var/www/html/roundcubemail-1.4.10/index.php( in /var/www/html/roundcubemail-1.4.10/plugins/enigma/enigma.php on line 448
[18-Jan-2021 00:50:14 America/Los_Angeles] PHP Warning:  proc_open() has been disabled for security reasons in /var/www/html/roundcubemail-1.4.10/vendor/pear$
[18-Jan-2021 00:50:14 -0800]: <858rpvd4> PHP Error: Enigma plugin: Unable to open GPG subprocess. in /var/www/html/roundcubemail-1.4.10/plugins/enigma/lib/en$
[18-Jan-2021 00:55:00 America/Los_Angeles] PHP Warning:  proc_open() has been disabled for security reasons in /var/www/html/roundcubemail-1.4.10/vendor/pear$
[18-Jan-2021 00:55:00 -0800]: <858rpvd4> PHP Error: Enigma plugin: Unable to open GPG subprocess. in /var/www/html/roundcubemail-1.4.10/plugins/enigma/lib/en$
```

How can I safely get this to work?

**Comment by alecpl** [comment]
proc_open() function is required. Change your PHP settings.
