### ISSUE TITLE
PHP 8.0.3 with roundcube -git master - Fatal Errors

### ISSUE THREAD

**Issue by reubenfarrelly** [roundcube/roundcubemail#7931]
This is with -git master as of today 10 March:

[10-Mar-2021 17:17:18 Australia/Sydney] PHP Fatal error:  Uncaught ValueError: max(): Argument #1 ($value) must contain at least one element in /var/www/roundcube.reub.net/htdocs/program/lib/Roundcube/rcube_result_index.php:192
Stack trace:
#0 /var/www/roundcube.reub.net/htdocs/program/lib/Roundcube/rcube_result_index.php(192): max()
#1 /var/www/roundcube.reub.net/htdocs/program/lib/Roundcube/rcube_imap.php(787): rcube_result_index->max()
#2 /var/www/roundcube.reub.net/htdocs/program/lib/Roundcube/rcube_imap.php(1348): rcube_imap->countmessages()
#3 /var/www/roundcube.reub.net/htdocs/program/actions/mail/check_recent.php(87): rcube_imap->folder_status()
#4 /var/www/roundcube.reub.net/htdocs/program/include/rcmail.php(275): rcmail_action_mail_check_recent->run()
#5 /var/www/roundcube.reub.net/htdocs/index.php(279): rcmail->action_handler()
#6 {main}
  thrown in /var/www/roundcube.reub.net/htdocs/program/lib/Roundcube/rcube_result_index.php on line 192
[10-Mar-2021 21:11:43 Australia/Sydney] PHP Warning:  Undefined variable $port in /var/www/roundcube.reub.net/htdocs/index.php on line 79

It appears to break checking of emails in mailboxes.

The imap server is a local Dovecot-2.3.14 on a Gentoo Linux installation with Apache and php-8.0.3.

**Comment by alecpl** [comment]
Fixed.
