### ISSUE TITLE
git master fatal error from Spoofchecker

### ISSUE THREAD

**Issue by gene-git** [roundcube/roundcubemail#7963]
As of this morning there is a fatal error when build with commit 2e88de27db2ce85cd21af234a8a5fb0d5c79205c from git master.

php: version 8.0.3

the log shows:

```
PHP Fatal error:  Uncaught Error: Class "Spoofchecker" not found in /usr/share/webapps/roundcubemail/program/lib/R
oundcube/rcube_spoofchecker.php:50
Stack trace:
#0 /usr/share/webapps/roundcubemail/program/actions/mail/index.php(1401): rcube_spoofchecker::check()
#1 /usr/share/webapps/roundcubemail/program/actions/mail/index.php(523): rcmail_action_mail_index::address_string(
)
#2 /usr/share/webapps/roundcubemail/program/actions/mail/list.php(122): rcmail_action_mail_index::js_message_list(
)
#3 /usr/share/webapps/roundcubemail/program/include/rcmail.php(275): rcmail_action_mail_list->run()
#4 /usr/share/webapps/roundcubemail/index.php(283): rcmail->action_handler()
#5 {main}
  thrown in /usr/share/webapps/roundcubemail/program/lib/Roundcube/rcube_spoofchecker.php on lin



```

**Comment by gene-git** [comment]
Last good commit was yesterday : commit 75c604aa3

So change happened today

thanks!

**Comment by alecpl** [comment]
PHP's Intl extension is required in git-master.

**Comment by gene-git** [comment]
Yep - that fixed it - the code Spoofchecker points that out as well (sorry I didn't read it earlier, my bad).
thank you kindly - all good now.
