### ISSUE TITLE
`Oops... something went wrong!' instead of email body

### ISSUE THREAD

**Issue by oleg-indeez** [roundcube/roundcubemail#8006]
Hi all!

It started yesterday evening: when I try to see my mail, it often print this error. If I select another mail and then back to this one, sometimes is shown as it should but it happens too rarely. In logs/error.log there're a lot of very similar errors:

```
[16-Apr-2021 10:37:07 Europe/Moscow] PHP Fatal error:  Uncaught IntlException: fopen(rcmail_string_replacer.php): failed to open stream: No such file or directory in [roundcube.git.root]program/lib/Roundcube/bootstrap.php:438
Stack trace:
#0 [roundcube.git.root]program/lib/Roundcube/bootstrap.php(438): fopen('rcmail_string_r...', 'r', true)
#1 [internal function]: rcube_autoload('rcmail_string_r...')
#2 [roundcube.git.root]program/lib/Roundcube/rcube_text2html.php(145): spl_autoload_call('rcmail_string_r...')
#3 [roundcube.git.root]program/lib/Roundcube/rcube_text2html.php(130): rcube_text2html->_converter('Stopping assp -...')
#4 [roundcube.git.root]program/lib/Roundcube/rcube_text2html.php(110): rcube_text2html->_convert()
#5 [roundcube.git.root]program/actions/mail/index.php(1073): rcube_text2html->get_html()
#6 [roundcube.git.root]program/actions/mail/index.php(1041): rcmail_action_mail_index::plain_body('Stopping assp -...', false, false)
#7 [roundcube.git.root]program/actions/mail/show.php(715): rcmail_action_mail_ind in [roundcube.git.root]program/lib/Roundcube/bootstrap.php on line 438
[16-Apr-2021 10:37:08 Europe/Moscow] PHP Fatal error:  Uncaught IntlException: filemtime(): stat failed for [roundcube.git.root]skins/elastic/ui.min.js in [roundcube.git.root]program/include/rcmail_output_html.php:1066
Stack trace:
#0 [roundcube.git.root]program/include/rcmail_output_html.php(1066): filemtime('/usr/local/www/...')
#1 [roundcube.git.root]program/include/rcmail_output_html.php(1027): rcmail_output_html->file_mod('skins/elastic/u...')
#2 [internal function]: rcmail_output_html->file_callback(Array)
#3 [roundcube.git.root]program/include/rcmail_output_html.php(1006): preg_replace_callback('!(src|href|back...', Array, '\n\nTEMPLOBJECT:6...')
#4 [roundcube.git.root]program/include/rcmail_output_html.php(1390): rcmail_output_html->fix_paths('\n\nTEMPLOBJECT:6...')
#5 [internal function]: rcmail_output_html->xml_command(Array)
#6 [roundcube.git.root]program/include/rcmail_output_html.php(1272): preg_replace_callback('/<roundcube:([-...', Array, '<roundcube:incl...')
#7 [roundcube.git.root]program/include/rcmail_out in [roundcube.git.root]program/include/rcmail_output_html.php on line 1066
```
having inspected catalog [roundcube.git.root]skins/elastic/ I found out there's no file ui.min.js, but there's ui.js. I've made soft link and it cures this partucular case, but.. Oops again!
```
[16-Apr-2021 10:49:11 Europe/Moscow] PHP Fatal error:  Uncaught IntlException: filemtime(): stat failed for [roundcube.git.root]plugins/jqueryui/themes/elastic/jquery-ui.min.css in [roundcube.git.root]program/include/rcmail_output_html.php:1066
Stack trace:
#0 [roundcube.git.root]program/include/rcmail_output_html.php(1066): filemtime('/usr/local/www/...')
#1 [roundcube.git.root]program/include/rcmail_output_html.php(1027): rcmail_output_html->file_mod('plugins/jqueryu...')
#2 [internal function]: rcmail_output_html->file_callback(Array)
#3 [roundcube.git.root]program/include/rcmail_output_html.php(1006): preg_replace_callback('!(src|href|back...', Array, '<!DOCTYPE html>...')
#4 [roundcube.git.root]program/include/rcmail_output_html.php(2090): rcmail_output_html->fix_paths('<!DOCTYPE html>...')
#5 [roundcube.git.root]program/include/rcmail_output_html.php(704): rcmail_output_html->_write('<!DOCTYPE html>...')
#6 [roundcube.git.root]program/include/rcmail_output_html.php(843): rcmail_output_html->write('<!DOCTYPE html>...') in [roundcube.git.root]program/include/rcmail_output_html.php on line 1066
```
the same error w/ another css that doesn't have a minified version. Now I try to correct the rcmail_output_html and, if success, propose  a patch

Have a nice day!

**Comment by alecpl** [comment]
Strange IntlException comes from Intl extension. It has nothing to do with the specific code. I think it might be some problem with PHP or php-intl extension or its dependencies.

What Roundcube version? What PHP version? What ICU version? Did it started after php  or some other package update (check what changed on the server)? Maybe reinstall PHP.

**Comment by oleg-indeez** [comment]
Thank you for a lightning reply! You're right - recently icu was updated. I've tried the following patch:
```--- program/include/rcmail_output_html.php.orig	2021-04-16 09:52:44.435001000 +0300
+++ program/include/rcmail_output_html.php	2021-04-16 11:04:44.526490000 +0300
@@ -1063,7 +1063,7 @@
         // use minified file if exists (not in development mode)
         if (!$this->devel_mode && !preg_match('/\.min\.' . $ext . '$/', $file)) {
             $minified_file = substr($file, 0, strlen($ext) * -1) . 'min.' . $ext;
-            if ($fs = @filemtime($this->assets_dir . $minified_file)) {
+            if (file_exists($this->assets_dir . $minified_file) && $fs = @filemtime($this->assets_dir . $minified_file)) {
                 return $minified_file . '?s=' . $fs;
             }
         }```
and it cured the situation a little, but not for all the mails. Now I try to recompile icu & php_intl

FYI: Roundcube Webmail 1.5-git [GIT 20210412.1215]; php 7.4.16; icu-69.1; works under php-fpm + apache 2.4.46 under FreeBSD 12.2-RELEASE-p6

**Comment by oleg-indeez** [comment]
seems that it helps and possibly  just forgot to reload php-fpm =(
Thank you once more for both answer & cool soft!
Have a nice day!
