### ISSUE TITLE
Roudcube doesn't work after upgrade to 1.5.0

### ISSUE THREAD

**Issue by Arturitu12** [roundcube/roundcubemail#8326]
Hello i just upgraded roundcube from 1.4.3 to 1.5.0 using installto.sh but i keep getting fatal error: 
>
```
[Sun Nov 21 14:30:11.294995 2021] [php:warn] [pid 26513] [client MY_IP] PHP Warning:  Undefined property: rcmail::$csrfToken in /var/www/roundcube/plugins/xframework/common/Plugin.php on line 1787
[Sun Nov 21 14:30:11.295198 2021] [php:warn] [pid 26513] [client MY_IP] PHP Warning:  Trying to access array offset on value of type null in /var/www/roundcube/plugins/xframework/common/Plugin.php on line 134
[Sun Nov 21 14:30:11.296490 2021] [php:error] [pid 26513] [client MY_IP] PHP Fatal error:  Uncaught Error: Undefined constant "zxcvbn" in /var/www/roundcube/plugins/password/config.inc.php:11\nStack trace:\n#0 /var/www/roun>
```
I trying to update plugins via composer but  `php composer.phar update --no-dev` returns 
`Could not open input file: composer.phar` ,

`composer install` tells me that: 
```
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
Your requirements could not be resolved to an installable set of packages.

```
`composer update` returns:
```
Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/
Updating dependencies (including require-dev)
PHP Fatal error:  Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php:84
Stack trace:
#0 [internal function]: array_merge()
#1 /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php(84): call_user_func_array()
#2 /usr/share/php/Composer/DependencyResolver/Solver.php(387): Composer\DependencyResolver\DefaultPolicy->selectPreferredPackages()
#3 /usr/share/php/Composer/DependencyResolver/Solver.php(740): Composer\DependencyResolver\Solver->selectAndInstall()
#4 /usr/share/php/Composer/DependencyResolver/Solver.php(231): Composer\DependencyResolver\Solver->runSat()
#5 /usr/share/php/Composer/Installer.php(489): Composer\DependencyResolver\Solver->solve()
#6 /usr/share/php/Composer/Installer.php(232): Composer\Installer->doInstall()
#7 /usr/share/php/Composer/Command/UpdateCommand.php(163): Composer\Installer->run()
#8 /usr/share/php/Symfony/Component/Console/Command/Command.php(255): Composer\Command\UpdateCommand->execute()
#9 /usr/share/php/Symfony/Component/Console/Application.php(934): Symfony\Component\Console\Command\Command->run()
#10 /usr/share/php/Symfony/Component/Console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#11 /usr/share/php/Composer/Console/Application.php(281): Symfony\Component\Console\Application->doRun()
#12 /usr/share/php/Symfony/Component/Console/Application.php(149): Composer\Console\Application->doRun()
#13 /usr/share/php/Composer/Console/Application.php(113): Symfony\Component\Console\Application->run()
#14 /usr/bin/composer(62): Composer\Console\Application->run()
#15 {main}
  thrown in /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php on line 84

Fatal error: Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php:84
Stack trace:
#0 [internal function]: array_merge()
#1 /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php(84): call_user_func_array()
#2 /usr/share/php/Composer/DependencyResolver/Solver.php(387): Composer\DependencyResolver\DefaultPolicy->selectPreferredPackages()
#3 /usr/share/php/Composer/DependencyResolver/Solver.php(740): Composer\DependencyResolver\Solver->selectAndInstall()
#4 /usr/share/php/Composer/DependencyResolver/Solver.php(231): Composer\DependencyResolver\Solver->runSat()
#5 /usr/share/php/Composer/Installer.php(489): Composer\DependencyResolver\Solver->solve()
#6 /usr/share/php/Composer/Installer.php(232): Composer\Installer->doInstall()
#7 /usr/share/php/Composer/Command/UpdateCommand.php(163): Composer\Installer->run()
#8 /usr/share/php/Symfony/Component/Console/Command/Command.php(255): Composer\Command\UpdateCommand->execute()
#9 /usr/share/php/Symfony/Component/Console/Application.php(934): Symfony\Component\Console\Command\Command->run()
#10 /usr/share/php/Symfony/Component/Console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#11 /usr/share/php/Composer/Console/Application.php(281): Symfony\Component\Console\Application->doRun()
#12 /usr/share/php/Symfony/Component/Console/Application.php(149): Composer\Console\Application->doRun()
#13 /usr/share/php/Composer/Console/Application.php(113): Symfony\Component\Console\Application->run()
#14 /usr/bin/composer(62): Composer\Console\Application->run()
#15 {main}
  thrown in /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php on line 84

```
What should i do?
Regards, Arturitu12

**Comment by amartinz** [comment]
I got the same issue and resolved it with upgrading `composer` to version 2.

https://getcomposer.org/download/

**Comment by alecpl** [comment]
Aside the composer issue, you have a syntax error in /var/www/roundcube/plugins/password/config.inc.php:11, the zxcvbn string should be in quotes.
