### ISSUE TITLE
Several PHP Warnings after Upgrade to 1.5.1 - PHP 8.0.13

### ISSUE THREAD

**Issue by kbojens** [roundcube/roundcubemail#8363]
RoundCube: 1.5.1
PHP-FPM: 8.0.13

There are several PHP Warnings in the error_log after upgrading to 1.5.1:

```
Undefined array key "data" in (…)/program/include/rcmail_action.php on line 686
Undefined property: rcube_message::$size in (…)/program/actions/mail/compose.php on line 696
Undefined property: rcube_message::$mime_id in (…)/program/actions/mail/compose.php on line 701
Undefined property: rcube_message::$ctype_secondary in (…)/program/actions/mail/compose.php on line 745
Undefined property: rcube_message::$ctype_secondary in (…)/program/actions/mail/compose.php on line 750
Undefined property: rcube_message::$ctype_secondary in (…)/program/actions/mail/compose.php on line 760
Attempt to read property "mdn_to" on null in (…)/program/include/rcmail_sendmail.php on line 1356
Undefined array key "" in (…)/program/lib/Roundcube/rcube_imap.php on line 1045
Undefined array key "_type" in (…)/program/actions/mail/search_contacts.php on line 90
Undefined array key "mimetype" in (…)/program/actions/mail/send.php on line 402
Trying to access array offset on value of type null in (…)/program/lib/Roundcube/rcube_plugin_api.php on line 371
```

**Comment by kbojens** [comment]
And now this:

```
PHP Fatal error:  Uncaught TypeError: strcasecmp(): Argument #1 ($string1) must be of type string, array given in (…)/program/lib/Roundcube/bootstrap.php:119
Stack trace:
#0 (…)/program/lib/Roundcube/bootstrap.php(119): strcasecmp()
#1 (…)/program/include/rcmail_action.php(1325): in_array_nocase()
#2 (…)/program/include/rcmail_action.php(1136): rcmail_action::render_folder_tree_select()
#3 (…)/program/actions/settings/folder_edit.php(148): rcmail_action::folder_selector()
#4 (…)/program/include/rcmail_output_html.php(1484): rcmail_action_settings_folder_edit::folder_form()
#5 [internal function]: rcmail_output_html->xml_command()
#6 (…)/program/include/rcmail_output_html.php(1322): preg_replace_callback()
#7 (…)/program/include/rcmail_output_html.php(825): rcmail_output_html->parse_xml()
#8(…)/program/include/rcmail_output_html.php(654): rcmail_output_html->parse()
#9 (…)/program/actions/settings/folder_edit.php(39): rcmail_output_html->send()
#10 (…)/program/include/rcmail.php(275): rcmail_action_settings_folder_edit->run()
#11 (…)/index.php(283): rcmail->action_handler()
#12 {main}
  thrown in (…)/program/lib/Roundcube/bootstrap.php on line 119
```

This happens whenever a folder is edited.

**Comment by alecpl** [comment]
Fixed.
