### ISSUE TITLE
Uncaught error when using tls:// URL in smtp_host config value

### ISSUE THREAD

**Issue by nagelp** [roundcube/roundcubemail#8396]
I've pulled latest master commit (f429b2681032c1c1c21694175f62fb57d8f41617) today and migrated my config.inc.php to the new key names. I then observed the following error in the errors.log:

```
[12-Jan-2022 17:38:33 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined method Net_SMTP::starttls() in /var/www/example.com/public_html/webmail/program/lib/Roundcube/rcube_smtp.php:167
Stack trace:
#0 /var/www/example.com/public_html/webmail/program/lib/Roundcube/rcube.php(284): rcube_smtp->connect()
#1 /var/www/example.com/public_html/webmail/program/lib/Roundcube/rcube.php(1784): rcube->smtp_init()
#2 /var/www/example.com/public_html/webmail/program/include/rcmail_sendmail.php(415): rcube->deliver_message()
#3 /var/www/example.com/public_html/webmail/program/actions/mail/send.php(245): rcmail_sendmail->deliver_message()
#4 /var/www/example.com/public_html/webmail/program/include/rcmail.php(275): rcmail_action_mail_send->run()
#5 /var/www/example.com/public_html/webmail/index.php(278): rcmail->action_handler()
#6 {main}
  thrown in /var/www/example.com/public_html/webmail/program/lib/Roundcube/rcube_smtp.php on line 167

```

This happened when I had configure smtp_host like so, and attempted to send an email.

```
$config['smtp_host'] = 'tls://mail.example.com:25';
```

When I remove the 'tls://' it starts working, but I would be worried whether it is then still encrypted or not.

**Comment by alecpl** [comment]
You need to update composer dependencies, pear/net_smtp in this case.

**Comment by nagelp** [comment]
Ah, that was it. Looks like I never updated the composer.json (just composer.json-dist), so even though I routinely ran composer update, I never got any updates... Thanks for pointing it out.
