### ISSUE TITLE
new_user_identity Plugin - Uncaught Error: Call to undefined function ldap_set_option()....:1999

### ISSUE THREAD

**Issue by Marco-Total** [roundcube/roundcubemail#8549]
Hello,

I would like to manage the identity of the users with the new_user_identity plugin. No matter what change I in the config, I always get the following error message after login:

`
[01-Jun-2022 16:24:03 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function ldap_set_option() in /var/www/roundcubemail/vendor/kolab/net_ldap3/lib/Net/LDAP3.php:1999
Stack trace:
#0 /var/www/roundcubemail/vendor/kolab/net_ldap3/lib/Net/LDAP3.php(577): Net_LDAP3->config_set_debug(true)
#1 /var/www/roundcubemail/vendor/kolab/net_ldap3/lib/Net/LDAP3.php(568): Net_LDAP3->config_set('debug', true)
#2 /var/www/roundcubemail/program/lib/Roundcube/rcube_ldap.php(279): Net_LDAP3->config_set(Array)
#3 /var/www/roundcubemail/plugins/new_user_identity/new_user_identity.php(153): rcube_ldap->__construct(Array, true, 'abc.com')
#4 /var/www/roundcubemail/plugins/new_user_identity/new_user_identity.php(143): new_user_identity_ldap_backend->__construct(Array, true, 'abc.com', 'uid')
#5 /var/www/roundcubemail/plugins/new_user_identity/new_user_identity.php(35): new_user_identity->init_ldap('localhost', 'marco')
#6 /var/www/roundcubemail/plugins/new_user_identity/new_user_identity.php(88): new_user_identity->lookup_user_name(Array)
#7 /v in /var/www/roundcubemail/vendor/kolab/net_ldap3/lib/Net/LDAP3.php on line 1999
`
I have enabled a ldap debugging in the config, however nothing is logged at all.
```
// system error reporting, sum of: 1 = log; 4 = show
$config['debug_level'] = 1;

// Log SQL queries
$config['sql_debug'] = true;

// Log IMAP conversation
$config['imap_debug'] = true;

// Log LDAP conversation
$config['ldap_debug'] = true;

// Log SMTP conversation
$config['smtp_debug'] = true;

```

**config/defaults.inc.php**
```
$config['ldap_public']['LDAP'] = [
    'name'              => 'LDAP',
    'hosts'             => 'ldaps://192.168.1.10:636',
    'ldap_version'      => 3,
    'user_specific'     => true,
    'bind_dn'           => 'cn=tspoex1,ou=Benutzer,ou=ORG,dc=abcintern,dc=net',
    'bind_pass'         => 'xxxxxxxxxxxxxx',
    'base_dn'           => 'ou=ORG,dc=abcintern,dc=net',
    'search_base_dn'    => 'ou=ORG,dc=abcintern,dc=net',
    'search_filter'     => '(&(objectClass=person)(uid=%u))',
    'scope'             => 'sub',
    'search_only'       => true,
    'hidden'            => true,
    'writable'          => false,
//    'filter'            => '(objectClass=person)',
    'search_fields'     => ['mail', 'cn'],
    'fieldmap' => [
    'name'        => 'cn',
    'surname'     => 'sn',
    'firstname'   => 'givenName',
    'jobtitle'    => 'title',
    ],
];
```

**plugins/new_user_identity/config.inc.php**
```
<?php

// The id of the address book to use to automatically set a
// user's full name in their new identity. (This should be an
// string, which refers to the $config['ldap_public'] array.)
$config['new_user_identity_addressbook'] = 'LDAPTSP';

// When automatically setting a user's full name in their
// new identity, match the user's login name against this field.
$config['new_user_identity_match'] = 'uid';

// Determine whether to import user's identities on each login.
// New user identity will be created for each e-mail address
// present in address book, but not assigned to any identity.
$config['new_user_identity_onlogin'] = 'false';

```

```
root@abcserver1:/var/www/roundcubemail# ls logs/ -alh
insgesamt 236K
drwxrwxr-x  2 www-data www-data 4,0K Jun  1 11:44 .
drwxr-xr-x 13 www-data www-data 4,0K Mai 25 10:15 ..
-rw-r--r--  1 www-data www-data  73K Jun  1 16:42 errors.log
-rw-r--r--  1 www-data www-data  164 Dez 29 23:29 .htaccess
-rw-r--r--  1 www-data www-data  50K Jun  1 16:42 imap.log
-rw-r--r--  1 www-data www-data  651 Mai 31 14:42 sendmail.log
-rw-r--r--  1 www-data www-data  78K Jun  1 16:42 sql.log

```

Can anyone give me a tip what I'm doing wrong?

Thanks, Marco

**Comment by Marco-Total** [comment]
Thank you very mutch!
