### ISSUE TITLE
PHP (8.1) Fatal error:  Uncaught TypeError: strtolower(): Argument #1 ($string) must be of type string, array given

### ISSUE THREAD

**Issue by ner00** [roundcube/roundcubemail#8803]
Roundcube 1.6
PHP 8.1

This error appears recurrently in the logs with PHP 8.1 and RC 1.6:

`PHP Fatal error:  Uncaught TypeError: strtolower(): Argument #1 ($string) must be of type string, array given in` https://github.com/roundcube/roundcubemail/blob/3f8c4680c3033d5e930333bc4276b0c455715b3f/program/lib/Roundcube/rcube_imap.php#L2139

Stack trace:
```
#0 /var/www/roundcube/program/lib/Roundcube/rcube_imap.php(2139): strtolower(Array)
#1 /var/www/roundcube/program/lib/Roundcube/rcube_imap.php(2268): rcube_imap->structure_part(Array, 1, '3')
#2 /var/www/roundcube/program/lib/Roundcube/rcube_imap.php(2110): rcube_imap->structure_part(Array, 1, '0', 'Received: (qmai...')
#3 /var/www/roundcube/program/lib/Roundcube/rcube_imap.php(2008): rcube_imap->structure_part(Array, 3, '', Object(rcube_message_header))
#4 /var/www/roundcube/program/lib/Roundcube/rcube_message.php(106): rcube_imap->get_message('66793')
#5 /var/www/roundcube/program/actions/mail/show.php(63): rcube_message->__construct('66793', 'INBOX', false)
#6 /var/www/roundcube/program/include/rcmail.php(275): rcmail_action_mail_show->run(Array)
#7 /var/www/roundcube/index.php(278): rcmail->action_handler()
#8 {main}
  thrown in /var/www/roundcube/program/lib/Roundcube/rcube_imap.php on line 2139
```

**Comment by ner00** [comment]
The error seems to be coming through here:
`PHP Warning:  Array to string conversion in /var/www/roundcube/program/lib/Roundcube/rcube_imap.php on line 2253`
https://github.com/roundcube/roundcubemail/blob/3f8c4680c3033d5e930333bc4276b0c455715b3f/program/lib/Roundcube/rcube_imap.php#L2253

I have started logging the data being parsed when it triggers the error seen in the log, and this is an example of the serialized array data that blows up:
`a:2:{i:0;s:8:"BOUNDARY";i:1;s:34:"=_edf62f47b25efce70b754aaf8d7196a1";}`

I'm not sure how that array ends up in the seconds part of the MIME type (`$part[8][1]`) or what that data actually represents. Full error log from the stuff mentioned above:

```
[25-Nov-2022 16:05:51 Europe/London] PHP Warning:  Array to string conversion in /var/www/roundcube/program/lib/Roundcube/rcube_imap.php on line 2253
[25-Nov-2022 16:05:51 Europe/London] PHP Fatal error:  Uncaught TypeError: strtolower(): Argument #1 ($string) must be of type string, array given in /var/www/roundcube/program/lib/Roundcube/rcube_imap.php:2139
Stack trace:
#0 /var/www/roundcube/program/lib/Roundcube/rcube_imap.php(2139): strtolower(Array)
#1 /var/www/roundcube/program/lib/Roundcube/rcube_imap.php(2278): rcube_imap->structure_part(Array, 1, '3')
#2 /var/www/roundcube/program/lib/Roundcube/rcube_imap.php(2110): rcube_imap->structure_part(Array, 1, '0', 'Received: (qmai...')
#3 /var/www/roundcube/program/lib/Roundcube/rcube_imap.php(2008): rcube_imap->structure_part(Array, 3, '', Object(rcube_message_header))
#4 /var/www/roundcube/program/lib/Roundcube/rcube_message.php(106): rcube_imap->get_message('66832')
#5 /var/www/roundcube/program/actions/mail/show.php(63): rcube_message->__construct('66832', 'INBOX', false)
#6 /var/www/roundcube/program/include/rcmail.php(275): rcmail_action_mail_show->run(Array)
#7 /var/www/roundcube/index.php(278): rcmail->action_handler()
#8 {main}
  thrown in /var/www/roundcube/program/lib/Roundcube/rcube_imap.php on line 2139
```

**Comment by alecpl** [comment]
Could you provide the whole BODYSTRUCTURE response?

**Comment by ner00** [comment]
> Could you provide the whole BODYSTRUCTURE response?

What's the proper way of gathering that information? `$config['imap_debug'] = true;` ?

**Comment by alecpl** [comment]
Yes.

**Comment by ner00** [comment]
Parts of the BODYSTRUCTURE (hostnames, IPs, domains, mail addresses) have been replaced for privacy reasons.

**errors.log**
```
[28-Nov-2022 08:40:13 Europe/London] PHP Warning:  Array to string conversion in /var/www/roundcube/program/lib/Roundcube/rcube_imap.php on line 2260
[28-Nov-2022 08:40:13 Europe/London] PHP Fatal error:  Uncaught TypeError: strtolower(): Argument #1 ($string) must be of type string, array given in /var/www/roundcube/program/lib/Roundcube/rcube_imap.php:2139
Stack trace:
#0 /var/www/roundcube/program/lib/Roundcube/rcube_imap.php(2139): strtolower(Array)
#1 /var/www/roundcube/program/lib/Roundcube/rcube_imap.php(2282): rcube_imap->structure_part(Array, 1, '3')
#2 /var/www/roundcube/program/lib/Roundcube/rcube_imap.php(2110): rcube_imap->structure_part(Array, 1, '0', 'Received: (qmai...')
#3 /var/www/roundcube/program/lib/Roundcube/rcube_imap.php(2008): rcube_imap->structure_part(Array, 3, '', Object(rcube_message_header))
#4 /var/www/roundcube/program/lib/Roundcube/rcube_message.php(106): rcube_imap->get_message('66855')
#5 /var/www/roundcube/program/actions/mail/show.php(63): rcube_message->__construct('66855', 'INBOX', false)
#6 /var/www/roundcube/program/include/rcmail.php(275): rcmail_action_mail_show->run(Array)
#7 /var/www/roundcube/index.php(278): rcmail->action_handler()
#8 {main}
  thrown in /var/www/roundcube/program/lib/Roundcube/rcube_imap.php on line 2139
```

**imap.log**
```
[28-Nov-2022 08:40:13 +0000]: <6q7r43am> [B3AA] S:  BODY[3.MIME] {3875}
[28-Nov-2022 08:40:13 +0000]: <6q7r43am> [B3AA] S: Received: (qmail 8373 invoked from network); 25 Nov 2022 18:25:42 -0000
Received: from filter-out.hostname.tld ([10.46.32.18]) (envelope-sender <sender@hostname.tld>) by mail-mta (qmail-mail-1.0.0) with ESMTPS for <extmail@exthost.tld>; 25 Nov 2022 18:25:42 -0000
Received: from server.hostname.tld ([10.22.223.224]) by filter.hostname.tld with esmtps (TLSv1.2:AES128-GCM-SHA256:128) (Exim 4.92) (envelope-from <sender@hostname.tld>) id 17oydN-0003TN-NE for extmail@exthost.tld; Fri, 25 Nov 2022 18:08:06 +0000
Received: from [10.223.22.1] (port=53578 helo=mail.domain.local) by server.hostname.tld with esmtpsa  (TLS1.2) tls TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (Exim 4.95) (envelope-from <sender@hostname.tld>) id 1oyd7Q-0004K1-Bg; Fri, 25 Nov 2022 18:08:05 +0000
Received: from 10.10.52.3 (rc.domain.local [10.10.52.3]) by mail.domain.local with ESMTPA ; Fri, 25 Nov 2022 18:08:05 +0000
Received-SPF: pass (mail-mta: SPF record at _spf.hostname.tld designates 10.46.32.18 as permitted sender)
X-Mail-RemoteIP: 10.46.32.18
X-Mail-AllowedSender-Action: 
X-Mail-Service: default
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/relaxed; d=hostname.tld ; s=default; h=Content-Type:Message-ID:Subject:Cc:To:From:Date:MIME-Version: Sender:Reply-To:Content-Transfer-Encoding:Content-ID:Content-Description: Resent-Date:Resent-From:Resent-Sender:Resent-To:Resent-Cc:Resent-Message-ID: In-Reply-To:References:List-Id:List-Help:List-Unsubscribe:List-Subscribe: List-Post:List-Owner:List-Archive; bh=Vrr/0cPkvRg1elgUnzbEH3vN39t5B99FReO1Wtz+YrU=; b=jgDvpw9z/m4xAOg0i7a/HLMeQO iH6ppXjyHG4ZaxximGp8lCBmuo7cxTBxYR2rtv7rMJJ8S0g9cdEkTGoCClbgCPm1Y9rtoWYQ8TbuS IVQiaNKLcoz35wS6JvFurDwce/lgLfaOOngb5JgwkDbR5gkloMA996eQRcAsNAlNtMkmk49pqHglp k2Zd5wLZnIrZGJZU5bGI3IVrpHMSrMafKhJywCHzlAihw5JXK85HN/0JmBIEZq/wC4LLA1n0oMuGW CZr0wDkMazxH+5YHP15UVeNCArUVu6eAzuKQY5+2REv/gLg6khi0qD5VPSnnsawCVtxhxaO9KeIdh yx41j41Q==;
MIME-Version: 1.0
Date: Fri, 25 Nov 2022 18:08:05 +0000
From: Sender <sender@hostname.tld>
To: Recipient A <extmail@exthost.tld>
Cc: Recipient B <otherusr@hostname.tld>
Subject: Test mail
Message-ID: <960564af959918c2a7b2e59bde1ebb79@hostname.tld>
X-Sender: sender@hostname.tld
Disposition-Notification-To: Sender <sender@hostname.tld>
Content-Type: multipart/mixed; boundary="=_0cc01990d46dea96cd7d692970fcbf82"
X-Originating-IP: 10.22.223.224
X-SpamExperts-Domain: smtp.hostname.tld
X-SpamExperts-Username: 10.85.44.0/24
X-SpamExperts-Outgoing-Class: whitelisted
X-SpamExperts-Outgoing-Evidence: rule/header
X-Recommended-Action: accept
X-Filter-ID: Pt3MvcO5N4iKaDQ5O6lkdGlMVN6RH8bjRMzItlySaT+MAgxozhPTW3j6VYs3eUy4/udx4p9vwL1V 9TC+Y/9+lX+aJEbcqKemqmSwovRrgYGpTDI+/Q5g97hNUsRlEHeHoQdwSkPkQOCxzocmuqjFYXZ3 TYARgdTrILoGn0jyBvpaa40DxZPJuLUk3zkVKd8p/KsEHMJFvah7gkI13aw6lygPlyTyNmZoyQHX 0Q0XZ/C/lxihTSrkHlloet1Lkg+tQKZ/6LmfyRFsGfqBKh4kLm7vTpOU7N35IoUFsevuiHiCIEHT TTdrwx1ReRlELySI+/8J+KTuCY2n8O3y1lSq/Na1SA/KSTnei6dal2m1m/aD5afFc/F49EU9bp0L uEIrtuKsOj85QWbm/Psk/IUAO0QMF99VlWOZVo1sbhkkbsVZ9Kt4of3B9DesjRVCqg5Zg074ocMI OqzwYzH6Ra8uslGLOI32AsXcRIdwzRHiHsMUQkkayy3LCi80do9jrdofprN3IMDMH/+QL4OWn9Cz 0g91gK+/QzK19qk8L965gvYNkBHrZLx9NP8Zp+qBec/LJLgeHyzXbJuPc5xhDsFtUcmk/n4Z5j5m fjlLleQTOnssuVaOsTohfZcZAm3ZkGbkZ0kLiI6sMZx+kxsjiGLZO2vfuoq10xrGT8RenWwEnwu+ nb46ox1e4y4H5dphyPyRwtgNvHbOAnFwNWqNgiBGsIefB5Bpj4S2NlJMsXG8bMsY74/00SIUridW 02b9FqU36MysKEwYUFcZMG8PeirD1Z+Orjf060NdjfYlvaLifjY79vV0MivTk1y7f/GY1OTe6YOQ Y96zDQNCX8X7cfbJORxwEiTVJqDh0qKoKsXx5lmMP4N0WKXh/a8vL71nshNCo67j4XVNh6NVWJPY Aeu+Zqbq38gZYIWXz7b8wCbWy3z31rGo+vW7Yp4JBUorJBDeoSyaA1TzQpMNBxbB7RLiYI7RCg6/ ZJ53lbW0kqr7CNqtXhzsSMa538dAeqBY0KJ1LZI+QBYU1Za+lycyQwNw9KSXGcMmN+uEX/USgexm NOk=
X-Report-Abuse-To: spam@master.hostname.tld
```

**Comment by alecpl** [comment]
That's not what I requested. Look for `BODYSTRUCTURE` in the imap.log.

**Comment by ner00** [comment]
> That's not what I requested. Look for `BODYSTRUCTURE` in the imap.log.

Sorry, this might be it:

**errors.log**
```
[28-Nov-2022 08:40:13 Europe/London] PHP Warning:  Array to string conversion in /var/www/roundcube/program/lib/Roundcube/rcube_imap.php on line 2253
[28-Nov-2022 08:40:13 Europe/London] PHP Fatal error:  Uncaught TypeError: strtolower(): Argument #1 ($string) must be of type string, array given in /var/www/roundcube/program/lib/Roundcube/rcube_imap.php:2139
Stack trace:
#0 /var/www/roundcube/program/lib/Roundcube/rcube_imap.php(2139): strtolower(Array)
#1 /var/www/roundcube/program/lib/Roundcube/rcube_imap.php(2282): rcube_imap->structure_part(Array, 1, '3')
#2 /var/www/roundcube/program/lib/Roundcube/rcube_imap.php(2110): rcube_imap->structure_part(Array, 1, '0', 'Received: (qmai...')
#3 /var/www/roundcube/program/lib/Roundcube/rcube_imap.php(2008): rcube_imap->structure_part(Array, 3, '', Object(rcube_message_header))
#4 /var/www/roundcube/program/lib/Roundcube/rcube_message.php(106): rcube_imap->get_message('66855')
#5 /var/www/roundcube/program/actions/mail/show.php(63): rcube_message->__construct('66855', 'INBOX', false)
#6 /var/www/roundcube/program/include/rcmail.php(275): rcmail_action_mail_show->run(Array)
#7 /var/www/roundcube/index.php(278): rcmail->action_handler()
#8 {main}
  thrown in /var/www/roundcube/program/lib/Roundcube/rcube_imap.php on line 2139
```

**imap.log**
```
[28-Nov-2022 08:40:13 +0000]: <6q7r43am> [B3AA] S: * 14 FETCH (UID 66855 RFC822.SIZE 7954 FLAGS () INTERNALDATE "28-Nov-2022 08:34:39 +0000" BODYSTRUCTURE (("TEXT" "PLAIN" ("CHARSET" "utf-8") NIL NIL "8bit" 232 7)("MESSAGE" "DISPOSITION-NOTIFICATION" ("NAME" "ATT-3.dat") NIL NIL "7bit" 269 NIL ("ATTACHMENT" ("FILENAME" "ATT-3.dat")))("MESSAGE" "RFC822" ("NAME" "Test mail.eml") NIL NIL "7bit" 3953 ("Fri, 25 Nov 2022 18:08:05 +0000" "Test mail" (("Sender" NIL "sender" "hostname.tld")) (("Sender" NIL "sender" "hostname.tld")) (("Sender" NIL "sender" "hostname.tld")) (("Recipient A" NIL "extmail" "exthost.tld")) (("Recipient B" NIL "otherusr" "hostname.tld")) NIL NIL "<960564af959918c2a7b2e59bde1ebb79@hostname.tld>") ( "MIXED" ("BOUNDARY" "=_0cc01990d46dea96cd7d692970fcbf82") NIL NIL) 1 NIL ("ATTACHMENT" ("FILENAME" "Test mail.eml"))) "REPORT" ("BOUNDARY" "=_RrjQxjLYBqTMnoYWobuYlwN") NIL NIL) BODY[HEADER.FIELDS (DATE FROM TO SUBJECT CONTENT-TYPE CC REPLY-TO LIST-POST DISPOSITION-NOTIFICATION-TO X-PRIORITY CONTENT-TRANSFER-ENCODING BCC IN-REPLY-TO MAIL-FOLLOWUP-TO MAIL-REPLY-TO MESSAGE-ID REFERENCES RESENT-BCC RETURN-PATH SENDER X-DRAFT-INFO)] {463}
```

**Comment by alecpl** [comment]
Fixed.
