### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Typed property DOMDocument::$documentElement must not be accessed before initialization in /var/www/roundcube/vendor/masterminds/html5/src/HTML5/Parser/DOMTreeBuilder.php:275

### ISSUE THREAD

**Issue by iUnstable0** [roundcube/roundcubemail#8826]
```
[22-Dec-2022 20:55:00 Asia/Krasnoyarsk] PHP Fatal error:  Uncaught Error: Typed property DOMDocument::$documentElement must not be accessed before initialization in /var/www/roundcube/vendor/masterminds/html5/src/HTML5/Parser/DOMTreeBuilder.php:275
Stack trace:
#0 /var/www/roundcube/vendor/masterminds/html5/src/HTML5/Parser/Tokenizer.php(399): Masterminds\HTML5\Parser\DOMTreeBuilder->startTag()
#1 /var/www/roundcube/vendor/masterminds/html5/src/HTML5/Parser/Tokenizer.php(141): Masterminds\HTML5\Parser\Tokenizer->tagName()
#2 /var/www/roundcube/vendor/masterminds/html5/src/HTML5/Parser/Tokenizer.php(82): Masterminds\HTML5\Parser\Tokenizer->consumeData()
#3 /var/www/roundcube/vendor/masterminds/html5/src/HTML5.php(161): Masterminds\HTML5\Parser\Tokenizer->parse()
#4 /var/www/roundcube/vendor/masterminds/html5/src/HTML5.php(89): Masterminds\HTML5->parse()
#5 /var/www/roundcube/program/lib/Roundcube/rcube_washtml.php(698): Masterminds\HTML5->loadHTML()
#6 /var/www/roundcube/program/actions/mail/index.php(977): rcube_washtml->wash()
#7 /var/www/roundcube/program/actions/mail/index.php(1021): rcmail_action_mail_index::wash_html()
#8 /var/www/roundcube/program/actions/mail/show.php(748): rcmail_action_mail_index::print_body()
#9 /var/www/roundcube/program/include/rcmail_output_html.php(1484): rcmail_action_mail_show::message_body()
#10 [internal function]: rcmail_output_html->xml_command()
#11 /var/www/roundcube/program/include/rcmail_output_html.php(1322): preg_replace_callback()
#12 /var/www/roundcube/program/include/rcmail_output_html.php(825): rcmail_output_html->parse_xml()
#13 /var/www/roundcube/program/include/rcmail_output_html.php(654): rcmail_output_html->parse()
#14 /var/www/roundcube/program/actions/mail/show.php(164): rcmail_output_html->send()
#15 /var/www/roundcube/program/include/rcmail.php(275): rcmail_action_mail_show->run()
#16 /var/www/roundcube/index.php(278): rcmail->action_handler()
#17 {main}
  thrown in /var/www/roundcube/vendor/masterminds/html5/src/HTML5/Parser/DOMTreeBuilder.php on line 275
```

this error happens when I try to open some emails, this is very weird as it never happened before now it just happened randomly for no reason, emails that used to work now wont open and instead throw that error

**Comment by iUnstable0** [comment]
Btw im using php 8.1 fpm nginx fastCGI (Im new to PHP I think I might've accidentally caused this but I'm not sure, what I'm sure is I never touched Roundcube internal PHP code only plugins code)

**Comment by iUnstable0** [comment]
```
Return-Path: <iunstable0@swisscows.email>
Delivered-To: big@gang.email
Received: from mail.falcon-utility.com
	by falcon-utility.com with LMTP
	id 3hrMNZMApWOSFSQAQqPMxQ
	(envelope-from <iunstable0@swisscows.email>)
	for <big@gang.email>; Fri, 23 Dec 2022 08:12:51 +0700
Authentication-Results: mail.falcon-utility.com;
	dkim=pass (2048-bit key; secure) header.d=swisscows.email header.i=@swisscows.email header.a=rsa-sha256 header.s=postfix header.b=RQeqfyw/;
	dkim-atps=neutral
Received: from localhost (localhost [127.0.0.1])
	by mail.falcon-utility.com (Postfix) with ESMTP id CB02A2C01D3
	for <big@gang.email>; Fri, 23 Dec 2022 08:12:51 +0700 (+07)
X-Virus-Scanned: Debian amavisd-new at falcon-utility.com
Received: from mail.falcon-utility.com ([127.0.0.1])
	by localhost (falcon-utility.com [127.0.0.1]) (amavisd-new, port 10024)
	with ESMTP id A5RaXx7MahbA for <big@gang.email>;
	Fri, 23 Dec 2022 08:12:51 +0700 (+07)
Authentication-Results: OpenDMARC; dmarc=pass (p=none dis=none) header.from=swisscows.email
Received-SPF: Pass (mailfrom) identity=mailfrom; client-ip=146.185.79.120; helo=mail-gate.swisscows.email; envelope-from=iunstable0@swisscows.email; receiver=<UNKNOWN> 
Received: from mail-gate.swisscows.email (mail-gate.swisscows.email [146.185.79.120])
	by mail.falcon-utility.com (Postfix) with ESMTPS id 6AB832C00B9
	for <big@gang.email>; Fri, 23 Dec 2022 08:12:46 +0700 (+07)
Received: from mail-gate (localhost [127.0.0.1])
	by mail-gate.swisscows.email (Proxmox) with ESMTP id 43E1421BAB
	for <big@gang.email>; Fri, 23 Dec 2022 02:12:45 +0100 (CET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=swisscows.email;
	s=postfix; t=1671757956;
	bh=BBrflOi4OjQDi5ueW/ZysrLCQ2CqJeZvM7B6bczZ/O0=;
	h=Date:From:To:Subject:In-Reply-To:References;
	b=RQeqfyw/QylIOOgD7vx0ZYmBTd4MmgfuRdL+Boxya8ZntHe5oCz/0ipjWFeM0ZzSw
	 WDIplDuoIrRqLpUchyN8jFZfUJ/6XdXK+duduR5sBmXaXEmgZLU0wE0LaaWkxTtQr4
	 mjIs0mwd3bn7I5rh0dMgrxUcPcrZpw7aUed4mH4TSMNHOMfXiML5fuKL9x4PP2CxFx
	 0A6Yg4tTIQt/nfdf1YYOlBGMnkq/O1k2hvQ1qIVSZUplByk2naCs9I6w5yXH0QA64W
	 MkQxDo8zv550xfFpxXyUYWf/WdpaBwz35PqZBswVv4luAjfClqyIS7uvgQEddmWJ5S
	 9BKQMZQ8Jv5Hw==
MIME-Version: 1.0
Date: Fri, 23 Dec 2022 01:12:36 +0000
From: iunstable0@swisscows.email
To: Jirayu Adisakdechakul <big@gang.email>
Subject: Re: Hi noob
In-Reply-To: <232fe80f2ae6f403f4b47fa910cb996b@gang.email>
References: <232fe80f2ae6f403f4b47fa910cb996b@gang.email>
Message-ID: <0ca76a9a972b97ec9af02756eb512c52@swisscows.email>
X-Sender: iunstable0@swisscows.email
Content-Type: multipart/alternative;
 boundary="=_59e046e5c4fd71a265562c29394e695a"

--=_59e046e5c4fd71a265562c29394e695a
Content-Transfer-Encoding: 7bit
Content-Type: text/plain; charset=US-ASCII;
 format=flowed



On 2022-12-23 01:11, Jirayu Adisakdechakul wrote:

> switch to gang, it's better

sure sure whatever

-- 
Sent via Swisscows.email.
My mails are safe. And yours?
--=_59e046e5c4fd71a265562c29394e695a
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset=UTF-8

<html><head><meta http-equiv=3D"Content-Type" content=3D"text/html; charset=
=3DUTF-8" /></head><body style=3D'font-size: 10pt; font-family: Verdana,Gen=
eva,sans-serif'>
<p id=3D"reply-intro">On 2022-12-23 01:11, Jirayu Adisakdechakul wrote:</p>
<blockquote type=3D"cite" style=3D"padding: 0 0.4em; border-left: #1010ff 2=
px solid; margin: 0">
<div class=3D"pre" style=3D"margin: 0; padding: 0; font-family: monospace">=
<span style=3D"white-space: nowrap;">switch&nbsp;to&nbsp;gang,&nbsp;it's&nb=
sp;better</span><br /><br /></div>
</blockquote>
<p>sure sure whatever</p>
<div id=3D"signature">-- <br />
<div class=3D"pre" style=3D"margin: 0; padding: 0; font-family: monospace">=
Sent via Swisscows.email.<br />My mails are safe. And yours?</div>
</div>
</body></html>

--=_59e046e5c4fd71a265562c29394e695a--
```

This is the full source of the email that shows error

**Comment by iUnstable0** [comment]
OK I tested it happens to HTML messages, not plaintext

**Comment by alecpl** [comment]
I'm unable to reproduce, but I created an upstream ticket https://github.com/Masterminds/html5-php/issues/220

**Comment by stof** [comment]
Taking the HTML content of that email (after decoding the quoted-printable encoding) and parsing it with the html5-php library does not produce any error. So the upstream report is not actionable.

**Comment by alecpl** [comment]
@iUnstable0 what PHP version exactly? Could you try with most recent PHP 8.2.x?

**Comment by iUnstable0** [comment]
> @iUnstable0 what PHP version exactly? Could you try with most recent PHP 8.2.x?

I just upgraded to php8.2-fpm and roundcube to 1.6.1 and the issue is fixed. Thanks!
