### ISSUE TITLE
Roundcube can't display text/plain messages

### ISSUE THREAD

**Issue by vadimkim** [roundcube/roundcubemail#8834]
Hello,

I have latest RC that works normally. I have updated PHP81 libraries and after that plain text messages can't be displayed. HTML messages are all OK. It seems some necessary library was acidentally removed while I was updating PHP. Roundcube error log:
```
[28-Dec-2022 09:12:31 Europe/Tallinn] PHP Fatal error:  Uncaught IntlException: fopen(rcmail_string_replacer.php): Failed to open stream: No such file or directory in /usr/local/www/roundcube/program/lib/Roundcube/bootstrap.php:442
Stack trace:
#0 /usr/local/www/roundcube/program/lib/Roundcube/bootstrap.php(442): fopen('rcmail_string_r...', 'r', true)
#1 /usr/local/www/roundcube/program/lib/Roundcube/rcube_text2html.php(148): rcube_autoload('rcmail_string_r...')
#2 /usr/local/www/roundcube/program/lib/Roundcube/rcube_text2html.php(133): rcube_text2html->converter('Hello,\n\nYour ce...')
#3 /usr/local/www/roundcube/program/lib/Roundcube/rcube_text2html.php(113): rcube_text2html->convert()
#4 /usr/local/www/roundcube/program/actions/mail/index.php(1074): rcube_text2html->get_html()
#5 /usr/local/www/roundcube/program/actions/mail/index.php(1043): rcmail_action_mail_index::plain_body('Hello,\n\nYour ce...', false, false)
#6 /usr/local/www/roundcube/program/actions/mail/show.php(748): rcmail_action_mail_index::print_body('Hello,\n\nYour ce...', Object(rcube_message_part), Array)
#7 /usr/local/www/roundcube/program/include/rcmail_output_html.php(1484): rcmail_action_mail_show::message_body(Array)
#8 [internal function]: rcmail_output_html->xml_command(Array)
#9 /usr/local/www/roundcube/program/include/rcmail_output_html.php(1322): preg_replace_callback('/<roundcube:([-...', Array, '<roundcube:incl...')
#10 /usr/local/www/roundcube/program/include/rcmail_output_html.php(825): rcmail_output_html->parse_xml('<roundcube:incl...')
#11 /usr/local/www/roundcube/program/include/rcmail_output_html.php(654): rcmail_output_html->parse('message', false)
#12 /usr/local/www/roundcube/program/actions/mail/show.php(164): rcmail_output_html->send('message', false)
#13 /usr/local/www/roundcube/program/include/rcmail.php(275): rcmail_action_mail_show->run(Array)
#14 /usr/local/www/roundcube/index.php(278): rcmail->action_handler()
#15 {main}
  thrown in /usr/local/www/roundcube/program/lib/Roundcube/bootstrap.php on line 442
```
Can you help me to define what is missing? Reinstalling roundcube didn't help. Thanks

**Comment by voojudev** [comment]
this should fix the bug
https://github.com/roundcube/roundcubemail/pull/8835

**Comment by vadimkim** [comment]
It works! Issue is closed. Thanks!
