### ISSUE TITLE
PHP error when logging in

### ISSUE THREAD

**Issue by bishnabob** [roundcube/roundcubemail#8850]
When logging in I get the "Oops... something went wrong!" page.

Errors.log shows:

[06-Jan-2023 10:10:12 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "INTL_IDNA_VARIANT_UTS46" in /var/www/mail/program/lib/Roundcube/rcube_utils.php:1146
Stack trace:                                                                                                                                                         
#0 /var/www/mail/program/lib/Roundcube/rcube_utils.php(1110): rcube_utils::idn_convert()                                                                             
#1 /var/www/mail/program/include/rcmail.php(752): rcube_utils::idn_to_ascii()                                                                                        
#2 /var/www/mail/index.php(119): rcmail->login()                                                                                                                     
#3 {main}                                                                                                                                                            
  thrown in /var/www/mail/program/lib/Roundcube/rcube_utils.php on line 1146   

I'm assuming this is a version compatibility issue somewhere, as it previously worked and has stopped at some point following an update to a dependency.

Can someone please help point me in the right direction?

**Comment by bishnabob** [comment]
php-intl is already installed:

php-intl is already the newest version (2:8.2+93+0~20221211.45+debian11~1.gbpdb4dcc).

**Comment by alecpl** [comment]
Make sure it is installed and enabled for the PHP version you execute Roundcube under.

**Comment by bishnabob** [comment]
You are correct - php8.2 installed, php8.1 enabled. Thanks for your help.
