### ISSUE TITLE
v1.6.1: Oops... something went wrong! when opening Mails

### ISSUE THREAD

**Issue by gunnarhaslinger** [roundcube/roundcubemail#8888]
Upgraded from 1.6.0 to 1.6.1 ... now experiencing "Oops... something went wrong!" Errors when trying to open certain Mails crafted for example by PHPMailer 6.5.1

Reverting to v1.6.0 solves the issue.
Disabling the authres_status plugins solves the issue in v1.6.1 (but plugin didn't change during upgrade).

Log says:
```
[25-Jan-2023 23:19:55 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function get_raw_body() on null in /var/www/roundcubemail/roundcubemail-current/plugins/authres_status/authres_status.php:427
Stack trace:
#0 /var/www/roundcubemail/roundcubemail-current/plugins/authres_status/authres_status.php(241): authres_status->get_authentication_status()
#1 /var/www/roundcubemail/roundcubemail-current/program/lib/Roundcube/rcube_plugin_api.php(518): authres_status->message_headers()
#2 /var/www/roundcubemail/roundcubemail-current/program/actions/mail/show.php(534): rcube_plugin_api->exec_hook()
#3 /var/www/roundcubemail/roundcubemail-current/program/include/rcmail_output_html.php(1484): rcmail_action_mail_show::message_headers()
#4 [internal function]: rcmail_output_html->xml_command()
#5 /var/www/roundcubemail/roundcubemail-current/program/include/rcmail_output_html.php(1322): preg_replace_callback()
#6 /var/www/roundcubemail/roundcubemail-current/program/include/rcmail_output_html.php(825): rcmail_output_html->parse_xml()
#7 /var/www/roundcubemail/rou in /var/www/roundcubemail/roundcubemail-current/plugins/authres_status/authres_status.php on line 427
```

**Comment by alecpl** [comment]
The plugin is not compatible with Roundcube 1.6. https://github.com/pimlie/authres_status/pull/60

**Comment by gunnarhaslinger** [comment]
Thanks @alecpl for the pointer to https://github.com/pimlie/authres_status/pull/60 ... I can confirm this small Code-Change worked for me and solves the issue.
