### ISSUE TITLE
QR code for non-ASCII-127 contacts cannot be generated

### ISSUE THREAD

**Issue by dilyanpalauzov** [roundcube/roundcubemail#9001]
When a contact contains non ASCII-127 character, the QR code for that contact cannot be generated.  /tmp/error.log contains that text.

I think the system insists on encoding the data in ISO-8859-1, which fails for non-ASCII-127.
```
[02-May-2023 10:59:26 UTC] PHP Fatal error:  Uncaught BaconQrCode\Exception\WriterException: Could not encode content to ISO-8859-1 in /roundcubemail-1.6.1/vendor/bacon/bacon-qr-code/src/Encoder/Encoder.php:614                    Stack trace:
#0 /roundcubemail-1.6.1/vendor/bacon/bacon-qr-code/src/Encoder/Encoder.php(527): BaconQrCode\Encoder\Encoder::append8BitBytes('BEGIN:VCARD\r\nVE...', Object(BaconQrCode\Common\BitArray), 'ISO-8859-1')
#1 /roundcubemail-1.6.1/vendor/bacon/bacon-qr-code/src/Encoder/Encoder.php(77): BaconQrCode\Encoder\Encoder::appendBytes('BEGIN:VCARD\r\nVE...', Object(BaconQrCode\Common\Mode), Object(BaconQrCode\Common\BitArray), 'ISO-8859-1')
#2 /roundcubemail-1.6.1/vendor/bacon/bacon-qr-code/src/Writer.php(54): BaconQrCode\Encoder\Encoder::encode('BEGIN:VCARD\r\nVE...', Object(BaconQrCode\Common\ErrorCorrectionLevel), 'ISO-8859-1', NULL)
#3 /roundcubemail-1.6.1/program/actions/contacts/qrcode.php(108): BaconQrCode\Writer->writeString('BEGIN:VCARD\r\nVE...')                                                                                                             #4 /roundcubemail-1.6.1/program/actions/contacts/qrcode.php(42): rcmail_action_contacts_qrcode::contact_qrcode(Array)                                                                                                                 #5 /roundcubemail-1.6.1/program/include/rcmail.php(282): rcmail_action_contacts_qrcode->run(Array)
#6 /roundcubemail-1.6.1/index.php(278): rcmail->action_handler()
#7 {main}                                                                                                            thrown in /roundcubemail-1.6.1/vendor/bacon/bacon-qr-code/src/Encoder/Encoder.php on line 614
[02-May-2023 10:59:40 UTC] PHP Fatal error:  Uncaught BaconQrCode\Exception\WriterException: Could not encode content to ISO-8859-1 in /roundcubemail-1.6.1/vendor/bacon/bacon-qr-code/src/Encoder/Encoder.php:614                    Stack trace:
#0 /roundcubemail-1.6.1/vendor/bacon/bacon-qr-code/src/Encoder/Encoder.php(527): BaconQrCode\Encoder\Encoder::append8BitBytes('BEGIN:VCARD\r\nVE...', Object(BaconQrCode\Common\BitArray), 'ISO-8859-1')
#1 /roundcubemail-1.6.1/vendor/bacon/bacon-qr-code/src/Encoder/Encoder.php(77): BaconQrCode\Encoder\Encoder::appendBytes('BEGIN:VCARD\r\nVE...', Object(BaconQrCode\Common\Mode), Object(BaconQrCode\Common\BitArray), 'ISO-8859-1') 
#2 /roundcubemail-1.6.1/vendor/bacon/bacon-qr-code/src/Writer.php(54): BaconQrCode\Encoder\Encoder::encode('BEGIN:VCARD\r\nVE...', Object(BaconQrCode\Common\ErrorCorrectionLevel), 'ISO-8859-1', NULL)                               #3 /roundcubemail-1.6.1/program/actions/contacts/qrcode.php(108): BaconQrCode\Writer->writeString('BEGIN:VCARD\r\nVE...')                                                                                                             #4 /roundcubemail-1.6.1/program/actions/contacts/qrcode.php(42): rcmail_action_contacts_qrcode::contact_qrcode(Array)                                                                                                                 #5 /roundcubemail-1.6.1/program/include/rcmail.php(282): rcmail_action_contacts_qrcode->run(Array)
#6 /roundcubemail-1.6.1/index.php(278): rcmail->action_handler()
#7 {main}                                                                                                            thrown in /roundcubemail-1.6.1/vendor/bacon/bacon-qr-code/src/Encoder/Encoder.php on line 614
```

PHP 8.1 with Roundcube 1.6.1

**Comment by alecpl** [comment]
Fixed.
