### ISSUE TITLE
Importing myContacts.vcf with php 8.2 and roundcube 1.6.1 results in error:   Oops... something went wrong

### ISSUE THREAD

**Issue by Hydranet** [roundcube/roundcubemail#9025]
Rocky Linux 9.2
PHP: 8.2
Roundcube: 1.6.1

When import a vcf contact file in Roundcube 1.6.1 with php 8.x I get the following error in the php log file.
```
[31-May-2023 16:41:42 UTC] PHP Fatal error:  Uncaught TypeError: array_map(): Argument #2 ($array) must be of type array, bool given in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php:205
Stack trace:
#0 /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php(205): array_map()
#1 /data/websites/roundcube/html/program/actions/contacts/import.php(181): rcube_vcard->get_assoc()
#2 /data/websites/roundcube/html/program/include/rcmail.php(282): rcmail_action_contacts_import->run()
#3 /data/websites/roundcube/html/index.php(278): rcmail->action_handler()
#4 {main}
  thrown in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 205
[31-May-2023 16:44:02 UTC] PHP Warning:  Undefined array key "require" in /data/websites/roundcube/html/program/lib/Roundcube/rcube_plugin_api.php on line 344

```
When I switch over to php 7.4 I am successfully able to import my vcf contact file but I get the following php warnings.
```
[31-May-2023 16:46:45 UTC] PHP Warning:  array_map(): Expected parameter 2 to be an array, bool given in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 205
[31-May-2023 16:46:45 UTC] PHP Warning:  array_diff(): Expected parameter 1 to be an array, null given in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 207
[31-May-2023 16:46:45 UTC] PHP Warning:  implode(): Invalid arguments passed in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 207
[31-May-2023 16:46:45 UTC] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 220
[31-May-2023 16:46:45 UTC] PHP Warning:  array_map(): Expected parameter 2 to be an array, bool given in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 205
[31-May-2023 16:46:45 UTC] PHP Warning:  array_diff(): Expected parameter 1 to be an array, null given in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 207
[31-May-2023 16:46:45 UTC] PHP Warning:  implode(): Invalid arguments passed in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 207
[31-May-2023 16:46:45 UTC] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 220
[31-May-2023 16:46:45 UTC] PHP Warning:  array_map(): Expected parameter 2 to be an array, bool given in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 205
[31-May-2023 16:46:45 UTC] PHP Warning:  array_diff(): Expected parameter 1 to be an array, null given in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 207
[31-May-2023 16:46:45 UTC] PHP Warning:  implode(): Invalid arguments passed in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 207
[31-May-2023 16:46:45 UTC] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 220
[31-May-2023 16:46:45 UTC] PHP Warning:  array_map(): Expected parameter 2 to be an array, bool given in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 205
[31-May-2023 16:46:45 UTC] PHP Warning:  array_diff(): Expected parameter 1 to be an array, null given in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 207
[31-May-2023 16:46:45 UTC] PHP Warning:  implode(): Invalid arguments passed in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 207
[31-May-2023 16:46:45 UTC] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 220
[31-May-2023 16:46:45 UTC] PHP Warning:  array_map(): Expected parameter 2 to be an array, bool given in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 205
[31-May-2023 16:46:45 UTC] PHP Warning:  array_diff(): Expected parameter 1 to be an array, null given in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 207
[31-May-2023 16:46:45 UTC] PHP Warning:  implode(): Invalid arguments passed in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 207
[31-May-2023 16:46:45 UTC] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 220
[31-May-2023 16:46:45 UTC] PHP Warning:  array_map(): Expected parameter 2 to be an array, bool given in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 205
[31-May-2023 16:46:45 UTC] PHP Warning:  array_diff(): Expected parameter 1 to be an array, null given in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 207
[31-May-2023 16:46:45 UTC] PHP Warning:  implode(): Invalid arguments passed in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 207
[31-May-2023 16:46:45 UTC] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 220
[31-May-2023 16:46:45 UTC] PHP Warning:  array_map(): Expected parameter 2 to be an array, bool given in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 205
[31-May-2023 16:46:45 UTC] PHP Warning:  array_diff(): Expected parameter 1 to be an array, null given in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 207
[31-May-2023 16:46:45 UTC] PHP Warning:  implode(): Invalid arguments passed in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 207
[31-May-2023 16:46:45 UTC] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 220
[31-May-2023 16:46:46 UTC] PHP Warning:  array_map(): Expected parameter 2 to be an array, bool given in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 205
[31-May-2023 16:46:46 UTC] PHP Warning:  array_diff(): Expected parameter 1 to be an array, null given in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 207
[31-May-2023 16:46:46 UTC] PHP Warning:  implode(): Invalid arguments passed in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 207
[31-May-2023 16:46:46 UTC] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /data/websites/roundcube/html/program/lib/Roundcube/rcube_vcard.php on line 220
```
It's not a huge problem since I don't import a new contact file on a daily basis. I thought I would report it in case no one else has run into this issue yet.

**Comment by alecpl** [comment]
Fixed.
