### ISSUE TITLE
Php error when accessing pages (tried the default and /installer)

### ISSUE THREAD

**Issue by SneznyKocur** [roundcube/roundcubemail#9345]
```
PHP Fatal error:  Uncaught Error: Call to undefined function mb_internal_encoding() in /var/www/html/program/lib/Roundcube/bootstrap.php:86
Stack trace:
#0 /var/www/html/program/include/iniset.php(78):require_once()
#1 /var/www/html/index.php(40): require_once('...')\n#2 {main}
thrown in /var/www/html/program/lib/Roundcube/bootstrap.php on line 86
```

Server version: Apache/2.4.57 (Debian)
PHP 8.2.7

`ls -la` output
```
-rwxrwxr-x  1 www-data www-data 213160 Feb 10 12:16 CHANGELOG.md
-rwxrwxr-x  1 www-data www-data  12661 Feb 10 12:16 INSTALL
-rwxrwxr-x  1 www-data www-data  35147 Feb 10 12:16 LICENSE
-rwxrwxr-x  1 www-data www-data   3853 Feb 10 12:16 README.md
-rwxrwxr-x  1 www-data www-data    967 Feb 10 12:16 SECURITY.md
drwxrwxr-x  7 www-data www-data   4096 Feb 10 12:16 SQL
-rwxrwxr-x  1 www-data www-data   4657 Feb 10 12:16 UPGRADING
drwxrwxr-x  2 www-data www-data   4096 Feb 10 12:16 bin
-rwxrwxr-x  1 www-data www-data    994 Feb 10 12:16 composer.json
-rwxrwxr-x  1 www-data www-data   1086 Feb 10 12:16 composer.json-dist
-rwxrwxr-x  1 www-data www-data  56361 Feb 10 12:16 composer.lock
drwxrwxr-x  2 www-data www-data   4096 Feb 10 12:16 config
-rwxrwxr-x  1 www-data www-data    615 Feb 10 12:13 index.nginx-debian.html
-rwxrwxr-x  1 www-data www-data  11199 Feb 10 12:16 index.php
drwxrwxr-x  3 www-data www-data   4096 Feb 10 12:16 installer
drwxrwxr-x  2 www-data www-data   4096 Feb 10 12:16 logs
drwxrwxr-x 37 www-data www-data   4096 Feb 10 12:16 plugins
drwxrwxr-x  8 www-data www-data   4096 Feb 10 12:16 program
drwxrwxr-x  3 www-data www-data   4096 Feb 10 12:16 public_html
drwxrwxr-x  3 www-data www-data   4096 Feb 10 12:16 skins
drwxrwxr-x  2 www-data www-data   4096 Feb 10 12:16 temp
drwxrwxr-x 14 www-data www-data   4096 Feb 10 12:16 vendor
```

i have setup the database with mariadb as per the instruction (mariadb should be a drop in replacement for mySQL)

**Comment by alecpl** [comment]
You need PHP `mbstring` extension.

**Comment by lordkage** [comment]
It's more than just installing the PHP extension, you need to also restart apache/httpd for the php module to pick it up.
