### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Unsupported operand types

### ISSUE THREAD

**Issue by Napsty** [roundcube/roundcubemail#9358]
We've seen a crash of Roundcube (1.5.5) when opening a specific e-mail. Roundcube logs a stack trace when this happens. At the same time PHP-FPM completely freezes and Roundcube is not usable anymore (until the processes eventually run into a timeout).

The request leading to the error:

```
"GET /?_task=mail&_action=get&_mbox=INBOX&_uid=56752&_token=FwNVLMUZsYjgU5IyQKAoxoFGOrWKdyWS&_part=2&_embed=1&_mimeclass=image HTTP/1.0" 200 16724 "https://roundcube.example.com/?_task=mail&_caps=pdf%3D1%2Cflash%3D0%2Ctiff%3D0%2Cwebp%3D1%2Cpgpmime%3D0&_uid=56752&_mbox=INBOX&_action=show" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
```

Stack trace:

```
[16-Feb-2024 11:03:03 Europe/Berlin] PHP Fatal error:  Uncaught Error: Unsupported operand types in /var/www/roundcubemail-1.5.5/program/lib/Roundcube/rcube.php:271
Stack trace:
#0 /var/www/roundcubemail-1.5.5/program/actions/utils/modcss.php(47): rcube->get_http_client()
#1 /var/www/roundcubemail-1.5.5/program/include/rcmail.php(275): rcmail_action_utils_modcss->run()
#2 /var/www/roundcubemail-1.5.5/index.php(283): rcmail->action_handler()
#3 {main}
  thrown in /var/www/roundcubemail-1.5.5/program/lib/Roundcube/rcube.php on line 271
[16-Feb-2024 11:03:03 Europe/Berlin] PHP Fatal error:  Uncaught Error: Unsupported operand types in /var/www/roundcubemail-1.5.5/program/lib/Roundcube/rcube.php:271
Stack trace:
#0 /var/www/roundcubemail-1.5.5/program/actions/utils/modcss.php(47): rcube->get_http_client()
#1 /var/www/roundcubemail-1.5.5/program/include/rcmail.php(275): rcmail_action_utils_modcss->run()
#2 /var/www/roundcubemail-1.5.5/index.php(283): rcmail->action_handler()
#3 {main}
  thrown in /var/www/roundcubemail-1.5.5/program/lib/Roundcube/rcube.php on line 271
[16-Feb-2024 11:03:03 Europe/Berlin] PHP Fatal error:  Uncaught Error: Unsupported operand types in /var/www/roundcubemail-1.5.5/program/lib/Roundcube/rcube.php:271
Stack trace:
#0 /var/www/roundcubemail-1.5.5/program/actions/utils/modcss.php(47): rcube->get_http_client()
#1 /var/www/roundcubemail-1.5.5/program/include/rcmail.php(275): rcmail_action_utils_modcss->run()
#2 /var/www/roundcubemail-1.5.5/index.php(283): rcmail->action_handler()
#3 {main}
  thrown in /var/www/roundcubemail-1.5.5/program/lib/Roundcube/rcube.php on line 271
[16-Feb-2024 11:03:03 Europe/Berlin] PHP Fatal error:  Uncaught Error: Unsupported operand types in /var/www/roundcubemail-1.5.5/program/lib/Roundcube/rcube.php:271
Stack trace:
#0 /var/www/roundcubemail-1.5.5/program/actions/utils/modcss.php(47): rcube->get_http_client()
#1 /var/www/roundcubemail-1.5.5/program/include/rcmail.php(275): rcmail_action_utils_modcss->run()
#2 /var/www/roundcubemail-1.5.5/index.php(283): rcmail->action_handler()
#3 {main}
  thrown in /var/www/roundcubemail-1.5.5/program/lib/Roundcube/rcube.php on line 271
[16-Feb-2024 11:03:03 Europe/Berlin] PHP Fatal error:  Uncaught Error: Unsupported operand types in /var/www/roundcubemail-1.5.5/program/lib/Roundcube/rcube.php:271
Stack trace:
#0 /var/www/roundcubemail-1.5.5/program/actions/utils/modcss.php(47): rcube->get_http_client()
#1 /var/www/roundcubemail-1.5.5/program/include/rcmail.php(275): rcmail_action_utils_modcss->run()
#2 /var/www/roundcubemail-1.5.5/index.php(283): rcmail->action_handler()
#3 {main}
  thrown in /var/www/roundcubemail-1.5.5/program/lib/Roundcube/rcube.php on line 271
```

Any idea what this could be? Is it potentially solved in 1.5.6 already (I haven't tried yet)? 

I will try to get access to the e-mail in question, not sure if it contains sensitive information though.

**Comment by alecpl** [comment]
Do you have `http_client` option set in `config.inc.php` or `defaults.inc.php`? To what value? This needs to be an array.

**Comment by alecpl** [comment]
Also, you might be using too new PHP version. Finally, 1.5 is in low maintenance mode, you should upgrade.

**Comment by Napsty** [comment]
The mail in question causing this is attached. Maybe it can also be reproduced in a newer RC version.

**Comment by Napsty** [comment]
The mail in question causing this is attached. Maybe it can also be reproduced in a newer RC version.
[1708057894.M99725P1909168.txt](https://github.com/roundcube/roundcubemail/files/14309709/1708057894.M99725P1909168.txt)

**Comment by alecpl** [comment]
Then your `defaults.inc.php` is not up to date. https://github.com/roundcube/roundcubemail/blob/release-1.5/config/defaults.inc.php#L816

I guess we could improve the code to not throw a fatal error in this case.

**Comment by alecpl** [comment]
The message works for me. It has a lot of inline images so it takes a few seconds initially and then a few more to load the images, but it works for me.

**Comment by alecpl** [comment]
The initial issue is solved. Closing.
