### ISSUE TITLE
any value other than $config['imap_cache'] = null; system fails.

### ISSUE THREAD

**Issue by gessel** [roundcube/roundcubemail#9639]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I can recreate the issue with all plugins disabled

### Describe the issue

setting a value for `imap_cache` other than null (tested `db`, `redis`, `apc`) results in error message 

```
Oops... something went wrong!
An internal error has occurred. Your request cannot be processed at this time.

For administrators: Please check the application and/or server error logs for more information.
```
the errors logged are

```
[Mon Sep 16 10:57:03.772702 2024] [proxy_fcgi:error] [pid 55322:tid 7955028957952] [remote 10.2.69.2:40280] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Undefined constant "redis" in /usr/local/www/roundcube/config/config.inc.php:87\nStack trace:\n#0 /usr/local/www/roundcube/program/lib/Roundcube/rcube_config.php(313): include()\n#1 /usr/local/www/roundcube/program/lib/Roundcube/rcube_config.php(202): rcube_config->load_from_file()\n#2 /usr/local/www/roundcube/program/lib/Roundcube/rcube_config.php(97): rcube_config->load()\n#3 /usr/local/www/roundcube/program/lib/Roundcube/rcube.php(117): rcube_config->__construct()\n#4 /usr/local/www/roundcube/program/include/rcmail.php(91): rcube->__construct()\n#5 /usr/local/www/roundcube/index.php(43): rcmail::get_instance()\n#6 {main}\n  thrown in /usr/local/www/roundcube/config/config.inc.php on line 87', referer: https://cube.blackrosetech.com/?_task=mail&_token=3Ek6jMn5eZYIbcgnhNm2gm2sLcwrEoaE


[Mon Sep 16 10:58:12.184729 2024] [proxy_fcgi:error] [pid 55322:tid 7955029475328] [remote 10.2.69.2:41930] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Undefined constant "db" in /usr/local/www/roundcube/config/config.inc.php:87\nStack trace:\n#0 /usr/local/www/roundcube/program/lib/Roundcube/rcube_config.php(313): include()\n#1 /usr/local/www/roundcube/program/lib/Roundcube/rcube_config.php(202): rcube_config->load_from_file()\n#2 /usr/local/www/roundcube/program/lib/Roundcube/rcube_config.php(97): rcube_config->load()\n#3 /usr/local/www/roundcube/program/lib/Roundcube/rcube.php(117): rcube_config->__construct()\n#4 /usr/local/www/roundcube/program/include/rcmail.php(91): rcube->__construct()\n#5 /usr/local/www/roundcube/index.php(43): rcmail::get_instance()\n#6 {main}\n  thrown in /usr/local/www/roundcube/config/config.inc.php on line 87', referer: https://cube.blackrosetech.com/?_task=mail&_token=3Ek6jMn5eZYIbcgnhNm2gm2sLcwrEoaE
```

### What browser(s) are you seeing the problem on?

Chrome

### What version of PHP are you using?

8.2.23

### What version of Roundcube are you using?

1.6.9,1

**Comment by gessel** [comment]
dude... thanks.  Duh.  working now.

Also, I could not find an example of a FreeBSD redis socket config so in case anyone is googling as I did for a `redis_hosts` config directive, this worked for me:

```
$config['redis_hosts'] = ['unix:///tmp/redis.sock'];
```
