### ISSUE TITLE
PHP Fatal Error When Trying To Fetch Certain "malformed" Messages

### ISSUE THREAD

**Issue by odixz** [roundcube/roundcubemail#9689]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I can recreate the issue with all plugins disabled

### Describe the issue

When trying to open certain email this notification appear in the preview window 

> Oops... something went wrong!
> An internal error has occurred. Your request cannot be processed at this time.
> 
> For administrators: Please check the application and/or server error logs for more information.

In roundcube error.log there is this entry : 
```
> PHP Fatal error:  Uncaught TypeError: strtolower(): Argument #1 ($string) must be of type string, array given in /var/www/webmail/program
> /lib/Roundcube/rcube_imap.php:2301
> Stack trace:
> #0 [internal function]: strtolower()
> #1 /var/www/webmail/program/lib/Roundcube/rcube_imap.php(2301): array_map()
> #2 /var/www/webmail/program/lib/Roundcube/rcube_imap.php(2091): rcube_imap->is_attachment_part()
> #3 /var/www/webmail/program/lib/Roundcube/rcube_imap.php(2008): rcube_imap->structure_part()
> #4 /var/www/webmail/program/lib/Roundcube/rcube_message.php(106): rcube_imap->get_message()
> #5 /var/www/webmail/program/actions/mail/show.php(63): rcube_message->__construct()
> #6 /var/www/webmail/program/include/rcmail.php(282): rcmail_action_mail_show->run()
> #7 /var/www/webmail/index.php(278): rcmail->action_handler()
> #8 {main}
>   thrown in /var/www/webmail/program/lib/Roundcube/rcube_imap.php on line 2301
```
And in imap.log: 
```
> FETCH (UID 81 RFC822.SIZE 6093164 FLAGS (\Seen) INTERNALDATE " 2-Nov-2024 10:39:28 +0700" BODYSTRUCTURE ((("TEXT" "PLAIN" ("CHARSET" "Windows-1252") NIL NIL "quoted-printable" 959 31)("TEXT" "HTML" ("CHARSET" "Windows-1252") NIL NIL "quoted-printable" 3842 85) "ALTERNATIVE" ("BOUNDARY" "_000_DM8PR16MB4421BE040E87573CD1B214DCB0572DM8PR16MB4421namp_") NIL NIL)("APPLICATION" "PDF" ("NAME" "HOLD_FI_IDN_UPS_PO_1545047,1545080_BAL HARB LG A 37\") NIL NIL "base64" 1992614 NIL ("attachment" ("FILENAME" "HOLD_FI_IDN_UPS_PO_1545047,1545080_BAL HARB LG A 37\")))("APPLICATION" "PDF" ("NAME" "=?Windows-1252?Q?HOLD=5FFI=5FIDN=5FUPS=5FPO=5F1545050=5FBAL_HARB_LG_A_89?= =?Windows-1252?Q?=94W_SF=5FOCT_29,2024.pdf?=") NIL NIL "base64" 1674332 NIL ("attachment" ("FILENAME" "=?Windows-1252?Q?HOLD=5FFI=5FIDN=5FUPS=5FPO=5F1545050=5FBAL_HARB_LG_A_89?= =?Windows-1252?Q?=94W_SF=5FOCT_29,2024.pdf?=")))("APPLICATION" "PDF" ("NAME" "HOLD_FI_IDN_UPS_PO_1545048_BAL HARB LG A 32\") NIL NIL "base64" 2404506 NIL ("attachment" ("FILENAME" "HOLD_FI_IDN_UPS_PO_1545048_BAL HARB LG A 32\"))) "MIXED" ("BOUNDARY" "_006_DM8PR16MB4421BE040E87573CD1B214DCB0572DM8PR16MB4421namp_") NIL NIL) BODY[HEADER.FIELDS (DATE FROM TO SUBJECT CONTENT-TYPE CC REPLY-TO LIST-POST DISPOSITION-NOTIFICATION-TO X-PRIORITY CONTENT-TRANSFER-ENCODING BCC IN-REPLY-TO MAIL-FOLLOWUP-TO MAIL-REPLY-TO MESSAGE-ID REFERENCES RESENT-BCC RETURN-PATH SENDER X-DRAFT-INFO)] {1165}
```

### What browser(s) are you seeing the problem on?

Chrome, Edge, Firefox

### What version of PHP are you using?

v8.1

### What version of Roundcube are you using?

v1.6.9

### PHP errors

in roundcube error.log:
```
> PHP Fatal error: Uncaught TypeError: strtolower(): Argument https://github.com/roundcube/roundcubemail/pull/1 ($string) must be of type string, array given in /var/www/webmail/program
> /lib/Roundcube/rcube_imap.php:2301
> Stack trace:
> #0 [internal function]: strtolower()
> https://github.com/roundcube/roundcubemail/pull/1 /var/www/webmail/program/lib/Roundcube/rcube_imap.php(2301): array_map()
> https://github.com/roundcube/roundcubemail/pull/2 /var/www/webmail/program/lib/Roundcube/rcube_imap.php(2091): rcube_imap->is_attachment_part()
> https://github.com/roundcube/roundcubemail/pull/3 /var/www/webmail/program/lib/Roundcube/rcube_imap.php(2008): rcube_imap->structure_part()
> https://github.com/roundcube/roundcubemail/pull/4 /var/www/webmail/program/lib/Roundcube/rcube_message.php(106): rcube_imap->get_message()
> https://github.com/roundcube/roundcubemail/pull/5 /var/www/webmail/program/actions/mail/show.php(63): rcube_message->__construct()
> https://github.com/roundcube/roundcubemail/pull/6 /var/www/webmail/program/include/rcmail.php(282): rcmail_action_mail_show->run()
> https://github.com/roundcube/roundcubemail/pull/7 /var/www/webmail/index.php(278): rcmail->action_handler()
> https://github.com/roundcube/roundcubemail/pull/8 {main}
> thrown in /var/www/webmail/program/lib/Roundcube/rcube_imap.php on line 2301
```
in roundcube imap.log:
```
> FETCH (UID 81 RFC822.SIZE 6093164 FLAGS (\Seen) INTERNALDATE " 2-Nov-2024 10:39:28 +0700" BODYSTRUCTURE ((("TEXT" "PLAIN" ("CHARSET" "Windows-1252") NIL NIL "quoted-printable" 959 31)("TEXT" "HTML" ("CHARSET" "Windows-1252") NIL NIL "quoted-printable" 3842 85) "ALTERNATIVE" ("BOUNDARY" "_000_DM8PR16MB4421BE040E87573CD1B214DCB0572DM8PR16MB4421namp_") NIL NIL)("APPLICATION" "PDF" ("NAME" "HOLD_FI_IDN_UPS_PO_1545047,1545080_BAL HARB LG A 37\") NIL NIL "base64" 1992614 NIL ("attachment" ("FILENAME" "HOLD_FI_IDN_UPS_PO_1545047,1545080_BAL HARB LG A 37\")))("APPLICATION" "PDF" ("NAME" "=?Windows-1252?Q?HOLD=5FFI=5FIDN=5FUPS=5FPO=5F1545050=5FBAL_HARB_LG_A_89?= =?Windows-1252?Q?=94W_SF=5FOCT_29,2024.pdf?=") NIL NIL "base64" 1674332 NIL ("attachment" ("FILENAME" "=?Windows-1252?Q?HOLD=5FFI=5FIDN=5FUPS=5FPO=5F1545050=5FBAL_HARB_LG_A_89?= =?Windows-1252?Q?=94W_SF=5FOCT_29,2024.pdf?=")))("APPLICATION" "PDF" ("NAME" "HOLD_FI_IDN_UPS_PO_1545048_BAL HARB LG A 32\") NIL NIL "base64" 2404506 NIL ("attachment" ("FILENAME" "HOLD_FI_IDN_UPS_PO_1545048_BAL HARB LG A 32\"))) "MIXED" ("BOUNDARY" "_006_DM8PR16MB4421BE040E87573CD1B214DCB0572DM8PR16MB4421namp_") NIL NIL) BODY[HEADER.FIELDS (DATE FROM TO SUBJECT CONTENT-TYPE CC REPLY-TO LIST-POST DISPOSITION-NOTIFICATION-TO X-PRIORITY CONTENT-TRANSFER-ENCODING BCC IN-REPLY-TO MAIL-FOLLOWUP-TO MAIL-REPLY-TO MESSAGE-ID REFERENCES RESENT-BCC RETURN-PATH SENDER X-DRAFT-INFO)] {1165}
```

**Comment by alecpl** [comment]
Confirmed. On master I see:
```
PHP Warning:  Undefined array key 2 in /home/alec/repos/roundcubemail/program/lib/Roundcube/rcube_imap.php on line 2307
PHP Fatal error:  Uncaught TypeError: strtolower(): Argument #1 ($string) must be of type string, array given in /home/alec/repos/roundcubemail/program/lib/Roundcube/rcube_imap.php:2285
```

**Comment by alecpl** [comment]
Something's wrong with that `BODYSTRUCTURE`. There's a few backslashes that are problematic, e.g. in this fragment `("NAME" "HOLD_FI_IDN_UPS_PO_1545047,1545080_BAL HARB LG A 37\") `. I'll need to investigate whether it is our bug or not. In any case it should not result in a fatal error.

**Comment by alecpl** [comment]
I think this is an imap server bug. Unless it's your copy paste error or there's something I'm missing.

The fatal error is fixed, but the message probably will not open properly anyway as the structure info is invalid.
